"""
categories.py
-------------
Sector categorization for companies in companies.py. Provides two lookups:

  SECTOR_OF[ticker]        -> category name (str)
  CATEGORIES[category]     -> list of (company_name, ticker) tuples

This is a curated, static categorization independent of Yahoo Finance's
`sector`/`industry` fields (which are frequently missing or inconsistent
for NSE tickers) — use this when you need reliable sector grouping, e.g.
for a category browser or filter.

Built in four passes:
  1. Parsed from companies.py section headers, consolidated from ~60 raw
     labels into a clean top-level set.
  2. "Placeholder" entries (unlisted subsidiaries or unrelated companies
     mapped to a real ticker as a search fallback, e.g. "Reliance General
     Insurance (unlisted, placeholder)" -> RELIANCE.NS) are excluded from
     category/name resolution for that ticker.
  3. A specific category is preferred over the generic "Diversified Large
     Cap" catch-all when a ticker has section entries in both.
  4. Manually-reviewed corrections for section headers that mixed unrelated
     business types (e.g. "Banking & Financial Services" originally mixed
     actual banks with exchanges/AMCs/insurers), plus explicit overrides
     for well-known large-caps whose names don't contain an obvious
     category keyword (e.g. "Infosys", "Maruti Suzuki India").

For day-to-day additions, add the new (name, ticker) tuple to the
relevant category list below — no need to touch companies.py's structure.
"""

CATEGORIES = {
    "Capital Goods & Industrials": [
        ("ABB India", "ABB.NS"),
        ("AIA Engineering", "AIAENG.NS"),
        ("Amber Enterprises India", "AMBER.NS"),
        ("Anupam Rasayan India", "ANURAS.NS"),
        ("Apar Industries", "APARINDS.NS"),
        ("Astral", "ASTRAL.NS"),
        ("Automotive Axles", "AUTOAXLES.NS"),
        ("BHEL (Bharat Heavy Electricals)", "BHEL.NS"),
        ("Bharat Dynamics", "BDL.NS"),
        ("Bharat Earth Movers (BEML)", "BEML.NS"),
        ("Blue Star", "BLUESTARCO.NS"),
        ("Bombay Dyeing & Manufacturing", "BOMDYEING.NS"),
        ("CG Power and Industrial Solutions", "CGPOWER.NS"),
        ("Camlin Fine Sciences", "CAMLINFINE.NS"),
        ("Carborundum Universal", "CARBORUNIV.NS"),
        ("Century Enka", "CENTENKA.NS"),
        ("Cochin Shipyard", "COCHINSHIP.NS"),
        ("Cords Cable Industries", "CORDSCABLE.NS"),
        ("Crompton Greaves Consumer Electricals", "CROMPTON.NS"),
        ("Cummins India", "CUMMINSIND.NS"),
        ("Deepak Fertilisers and Petrochemicals", "DEEPAKFERT.NS"),
        ("Diamond Power Infrastructure", "DIAPOWER.NS"),
        ("Dixon Technologies", "DIXON.NS"),
        ("EMS Limited", "EMSLIMITED.NS"),
        ("Elgi Equipments", "ELGIEQUIP.NS"),
        ("Engineers India", "ENGINERSIN.NS"),
        ("Fiem Industries", "FIEMIND.NS"),
        ("Finolex Cables", "FINCABLES.NS"),
        ("Finolex Industries", "FINPIPE.NS"),
        ("GE T&D India", "GET&D.NS"),
        ("GHCL", "GHCL.NS"),
        ("Gabriel India", "GABRIEL.NS"),
        ("Ganesh Housing Corporation", "GANESHHOUC.NS"),
        ("Garden Reach Shipbuilders & Engineers", "GRSE.NS"),
        ("Graphite India", "GRAPHITE.NS"),
        ("Greaves Cotton", "GREAVESCOT.NS"),
        ("Grindwell Norton", "GRINDWELL.NS"),
        ("HEG", "HEG.NS"),
        ("Himadri Speciality Chemical", "HSCL2.NS"),
        ("Hindustan Shipyard", "HSCL.NS"),
        ("Hitachi Energy India", "POWERINDIA.NS"),
        ("Honeywell Automation India", "HONAUT.NS"),
        ("Igarashi Motors India", "IGARASHI.NS"),
        ("Ion Exchange (India)", "IONEXCHANG.NS"),
        ("Ircon International", "IRCON.NS"),
        ("Jamna Auto Industries", "JAMNAAUTO.NS"),
        ("KEI Industries", "KEI.NS"),
        ("Kirloskar Brothers", "KIRLOSBROS.NS"),
        ("Kirloskar Oil Engines", "KIRLOSENG.NS"),
        ("Kirloskar Pneumatic", "KIRLPNU.NS"),
        ("Larsen & Toubro", "LT.NS"),
        ("Mazagon Dock Shipbuilders", "MAZDOCK.NS"),
        ("Meghmani Organics", "MEGH.NS"),
        ("Mishra Dhatu Nigam", "MIDHANI.NS"),
        ("NBCC India", "NBCC.NS"),
        ("Neogen Chemicals", "NEOGEN.NS"),
        ("Nocil", "NOCIL.NS"),
        ("Orient Electric", "ORIENTELEC.NS"),
        ("PCBL (Phillips Carbon Black)", "PCBL.NS"),
        ("Paramount Communications", "PARACABLES.NS"),
        ("Polycab India", "POLYCAB.NS"),
        ("Praj Industries", "PRAJIND.NS"),
        ("Privi Speciality Chemicals", "PRIVISCL.NS"),
        ("RITES", "RITES.NS"),
        ("RR Kabel", "RRKABEL.NS"),
        ("Rail Vikas Nigam", "RVNL.NS"),
        ("SKF India", "SKFINDIA.NS"),
        ("Schaeffler India", "SCHAEFFLER.NS"),
        ("Setco Automotive", "SETCO.NS"),
        ("Steel Strips Wheels", "SSWL.NS"),
        ("Sundram Fasteners", "SUNDRMFAST.NS"),
        ("Suprajit Engineering", "SUPRAJIT.NS"),
        ("Supreme Industries", "SUPREMEIND.NS"),
        ("Talbros Automotive Components", "TALBROAUTO.NS"),
        ("Texmaco Rail & Engineering", "TEXRAIL.NS"),
        ("Thermax", "THERMAX.NS"),
        ("Timken India", "TIMKEN.NS"),
        ("Titagarh Rail Systems", "TITAGARH.NS"),
        ("Triveni Turbine", "TRITURBINE.NS"),
        ("Universal Cables", "UNIVCABLES.NS"),
        ("V-Guard Industries", "VGUARD.NS"),
        ("VA Tech Wabag", "WABAG.NS"),
        ("Vardhman Special Steels", "VSSL.NS"),
        ("Vishnu Prakash R Punglia", "VPRPL.NS"),
        ("Wabco India (Sew Eurodrive)", "WABCOINDIA.NS"),
        ("Wheels India", "WHEELS.NS"),
        ("Whirlpool of India", "WHIRLPOOL.NS"),
        ("ZF Commercial Vehicle Control Systems India", "ZFCVINDIA.NS"),
    ],
    "FMCG & Consumer Goods": [
        ("Aditya Birla Fashion and Retail", "ABFRL.NS"),
        ("Akzo Nobel India", "AKZOINDIA.NS"),
        ("Asian Paints", "ASIANPAINT.NS"),
        ("Avalon Technologies", "AVALON.NS"),
        ("Avenue Supermarts (DMart)", "DMART.NS"),
        ("Bajaj Consumer Care", "BAJAJCON.NS"),
        ("Bajaj Electricals", "BAJAJELEC.NS"),
        ("Bata India", "BATAINDIA.NS"),
        ("Berger Paints India", "BERGEPAINT.NS"),
        ("Bikaji Foods International", "BIKAJI.NS"),
        ("Butterfly Gandhimathi Appliances", "BUTTERFLY.NS"),
        ("CCL Products India", "CCL.NS"),
        ("Campus Activewear", "CAMPUS.NS"),
        ("Cello World", "CELLO.NS"),
        ("Colgate-Palmolive India", "COLPAL.NS"),
        ("Cyient DLM", "CYIENTDLM.NS"),
        ("Dabur India", "DABUR.NS"),
        ("Emami", "EMAMILTD.NS"),
        ("Gillette India", "GILLETTE.NS"),
        ("Godfrey Phillips India", "GODFRYPHLP.NS"),
        ("Godrej Consumer Products", "GODREJCP.NS"),
        ("Goldiam International", "GOLDIAM.NS"),
        ("Havells India", "HAVELLS.NS"),
        ("Hawkins Cookers", "HAWKINCOOK.NS"),
        ("Hindustan Unilever", "HINDUNILVR.NS"),
        ("Hindware Home Innovation", "HINDWAREAP.NS"),
        ("Honasa Consumer (Mamaearth)", "HONASA.NS"),
        ("IFB Industries", "IFBIND.NS"),
        ("IKIO Lighting", "IKIO.NS"),
        ("ITC", "ITC.NS"),
        ("Indigo Paints", "INDIGOPNTS.NS"),
        ("Jubilant Foodworks", "JUBLFOOD.NS"),
        ("Jyothy Labs", "JYOTHYLAB.NS"),
        ("Kalyan Jewellers India", "KALYANKJIL.NS"),
        ("Kansai Nerolac Paints", "KANSAINER.NS"),
        ("Kaynes Technology India", "KAYNES.NS"),
        ("Khadim India", "KHADIM.NS"),
        ("Landmark Cars", "LANDMARK.NS"),
        ("Liberty Shoes", "LIBERTSHOE.NS"),
        ("Marico", "MARICO.NS"),
        ("Metro Brands", "METROBRAND.NS"),
        ("Mirza International", "MIRZAINT.NS"),
        ("Nestle India", "NESTLEIND.NS"),
        ("Nilkamal", "NILKAMAL.NS"),
        ("PC Jeweller", "PCJEWELLER.NS"),
        ("PG Electroplast", "PGEL.NS"),
        ("Procter & Gamble Hygiene and Health Care", "PGHH.NS"),
        ("Radico Khaitan", "RADICO.NS"),
        ("Rajesh Exports", "RAJESHEXPO.NS"),
        ("Relaxo Footwears", "RELAXO.NS"),
        ("Renaissance Global", "RGL.NS"),
        ("Safari Industries (India)", "SAFARI.NS"),
        ("Senco Gold", "SENCO.NS"),
        ("Shalimar Paints", "SHALPAINTS.NS"),
        ("Sheela Foam (Sleepwell)", "SFL.NS"),
        ("Shoppers Stop", "SHOPERSTOP.NS"),
        ("Shrenuj & Company", "SHRENUJ.NS"),
        ("Stove Kraft", "STOVEKRAFT.NS"),
        ("Symphony", "SYMPHONY.NS"),
        ("Syrma SGS Technology", "SYRMA.NS"),
        ("TTK Prestige", "TTKPRESTIG.NS"),
        ("Tata Consumer Products", "TATACONSUM.NS"),
        ("Thangamayil Jewellery", "THANGAMAYL.NS"),
        ("Titan Company", "TITAN.NS"),
        ("United Breweries", "UBL.NS"),
        ("United Spirits", "MCDOWELL-N.NS"),
        ("V-Mart Retail", "VMART.NS"),
        ("V2 Retail", "V2RETAIL.NS"),
        ("VIP Industries", "VIPIND.NS"),
        ("Vaibhav Global", "VAIBHAVGBL.NS"),
        ("Varun Beverages", "VBL.NS"),
        ("Vedant Fashions (Manyavar)", "VEDANTFASHN.NS"),
        ("Voltas", "VOLTAS.NS"),
        ("Zydus Wellness", "ZYDUSWELL.NS"),
    ],
    "NBFC & Financial Services": [
        ("360 One WAM (IIFL Wealth)", "360ONE.NS"),
        ("5paisa Capital", "5PAISA.NS"),
        ("Aditya Birla Capital", "ABCAPITAL.NS"),
        ("Aditya Birla Sun Life AMC", "ABSLAMC.NS"),
        ("Anand Rathi Wealth", "ANANDRATHI.NS"),
        ("Angel One", "ANGELONE.NS"),
        ("BSE Limited", "BSE.NS"),
        ("Bajaj Finance", "BAJFINANCE.NS"),
        ("Bajaj Finserv", "BAJAJFINSV.NS"),
        ("Bajaj Holdings & Investment", "BAJAJHLDNG.NS"),
        ("CARE Ratings", "CARERATING.NS"),
        ("CRISIL", "CRISIL.NS"),
        ("Can Fin Homes", "CANFINHOME.NS"),
        ("Capri Global Capital", "CGCL.NS"),
        ("Central Depository Services", "CDSL.NS"),
        ("Chola Investment and Finance", "CHOLAFIN.NS"),
        ("Cholamandalam Financial Holdings", "CHOLAHLDNG.NS"),
        ("Computer Age Management Services", "CAMS.NS"),
        ("Edelweiss Financial Services", "EDELWEISS.NS"),
        ("Five-Star Business Finance", "FIVESTAR.NS"),
        ("GIC Housing Finance", "GICHSGFIN.NS"),
        ("General Insurance Corporation of India", "GICRE.NS"),
        ("Geojit Financial Services", "GEOJITFSL.NS"),
        ("Go Digit General Insurance", "GODIGIT.NS"),
        ("HDFC Asset Management Company", "HDFCAMC.NS"),
        ("HDFC Life Insurance", "HDFCLIFE.NS"),
        ("ICICI Lombard General Insurance", "ICICIGI.NS"),
        ("ICICI Prudential Life Insurance", "ICICIPRULI.NS"),
        ("ICRA", "ICRA.NS"),
        ("IIFL Finance", "IIFL.NS"),
        ("IIFL Securities", "IIFLSEC.NS"),
        ("Indiabulls Housing Finance (Sammaan Capital)", "SAMMAANCAP.NS"),
        ("Indian Energy Exchange", "IEX.NS"),
        ("Indostar Capital Finance", "INDOSTAR.NS"),
        ("JM Financial", "JMFINANCIL.NS"),
        ("KFin Technologies", "KFINTECH.NS"),
        ("L&T Finance Holdings", "LTF.NS"),
        ("LIC Housing Finance", "LICHSGFIN.NS"),
        ("Life Insurance Corporation of India", "LICI.NS"),
        ("MAS Financial Services", "MASFIN.NS"),
        ("Mahindra & Mahindra Financial Services", "M&MFIN.NS"),
        ("Manappuram Finance", "MANAPPURAM.NS"),
        ("Max Financial Services", "MFSL.NS"),
        ("Medi Assist Healthcare Services", "MEDIASSIST.NS"),
        ("Motilal Oswal Financial Services", "MOTILALOFS.NS"),
        ("Multi Commodity Exchange of India", "MCX.NS"),
        ("Muthoot Finance", "MUTHOOTFIN.NS"),
        ("National Securities Depository", "NSDL.NS"),
        ("New India Assurance", "NIACL.NS"),
        ("Nippon Life India Asset Management", "NAM-INDIA.NS"),
        ("Niva Bupa Health Insurance", "NIVABUPA.NS"),
        ("Nuvama Wealth Management", "NUVAMA.NS"),
        ("PB Fintech (Policybazaar)", "POLICYBZR.NS"),
        ("PNB Housing Finance", "PNBHOUSING.NS"),
        ("Piramal Enterprises", "PEL.NS"),
        ("Poonawalla Fincorp", "POONAWALLA.NS"),
        ("Prudent Corporate Advisory Services", "PRUDENT.NS"),
        ("REC Limited", "RECLTD.NS"),
        ("Reliance Capital", "RELCAPITAL.NS"),
        ("Repco Home Finance", "REPCOHOME.NS"),
        ("SBFC Finance", "SBFC.NS"),
        ("SBI Cards and Payment Services", "SBICARD.NS"),
        ("SBI Life Insurance", "SBILIFE.NS"),
        ("SMC Global Securities", "SMCGLOBAL.NS"),
        ("SMIFS Capital Markets", "SMIFS.NS"),
        ("Satin Creditcare Network", "SATIN.NS"),
        ("Shriram Finance", "SHRIRAMFIN.NS"),
        ("Spandana Sphoorty Financial", "SPANDANA.NS"),
        ("Star Health and Allied Insurance", "STARHEALTH.NS"),
        ("Sundaram Finance", "SUNDARMFIN.NS"),
        ("Tata Investment Corporation", "TATAINVEST.NS"),
        ("UTI Asset Management Company", "UTIAMC.NS"),
    ],
    "Telecom, Media & Internet": [
        ("Aadhar Housing Finance", "AADHARHFC.NS"),
        ("Aptus Value Housing Finance India", "APTUS.NS"),
        ("Avanse Financial Services", "AVANSE.NS"),
        ("Awfis Space Solutions", "AWFIS.NS"),
        ("Balaji Telefilms", "BALAJITELE.NS"),
        ("Barbeque Nation Hospitality", "BARBEQUE.NS"),
        ("Bharti Airtel", "BHARTIARTL.NS"),
        ("CarTrade Tech", "CARTRADE.NS"),
        ("Chalet Hotels", "CHALET.NS"),
        ("Concord Enviro Systems", "CONCORDBIO.NS"),
        ("CreditAccess Grameen", "CREDITACC.NS"),
        ("D B Corp (Dainik Bhaskar)", "DBCORP.NS"),
        ("Delhivery", "DELHIVERY.NS"),
        ("Den Networks", "DEN.NS"),
        ("Devyani International", "DEVYANI.NS"),
        ("Dish TV India", "DISHTV.NS"),
        ("EIH (Oberoi Hotels)", "EIHOTEL.NS"),
        ("ESAF Small Finance Bank", "ESAFSFB.NS"),
        ("EaseMyTrip (Easy Trip Planners)", "EASEMYTRIP.NS"),
        ("Entertainment Network India (Radio Mirchi)", "ENIL.NS"),
        ("FSN E-Commerce Ventures (Nykaa)", "NYKAA.NS"),
        ("FirstCry (Brainbees Solutions)", "FIRSTCRY.NS"),
        ("Fusion Micro Finance", "FUSION.NS"),
        ("Garuda Construction and Engineering", "GARUDA.NS"),
        ("Go Fashion (India)", "GOCOLORS.NS"),
        ("HT Media", "HTMEDIA.NS"),
        ("Hathway Cable & Datacom", "HATHWAY.NS"),
        ("Home First Finance Company India", "HOMEFIRST.NS"),
        ("India Shelter Finance Corporation", "INDIASHLTR.NS"),
        ("Indiamart Intermesh", "INDIAMART.NS"),
        ("Indian Hotels Company", "INDHOTEL.NS"),
        ("Ixigo (Le Travenues Technology)", "IXIGO.NS"),
        ("Jagran Prakashan", "JAGRAN.NS"),
        ("Jio Financial Services", "JIOFIN.NS"),
        ("Just Dial", "JUSTDIAL.NS"),
        ("Lemon Tree Hotels", "LEMONTREE.NS"),
        ("Mahindra Holidays & Resorts India", "MHRIL.NS"),
        ("MapMyIndia (CE Info Systems)", "MAPMYINDIA.NS"),
        ("Matrimony.com", "MATRIMONY.NS"),
        ("MobiKwik (One MobiKwik Systems)", "MOBIKWIK.NS"),
        ("Music Broadcast (Radio City)", "MUSICBROAD.NS"),
        ("Nazara Technologies", "NAZARA.NS"),
        ("Network18 Media & Investments", "NETWORK18.NS"),
        ("Northern Arc Capital", "NORTHARC.NS"),
        ("Ola Electric Mobility", "OLAELEC.NS"),
        ("One97 Communications (Paytm)", "PAYTM.NS"),
        ("Ortel Communications", "ORTEL.NS"),
        ("PN Gadgil Jewellers", "PNGJL.NS"),
        ("PVR (legacy, merged into PVR Inox)", "PVR.NS"),
        ("PVR Inox", "PVRINOX.NS"),
        ("Restaurant Brands Asia (Burger King India)", "RBA.NS"),
        ("Sagility India", "SAGILITY.NS"),
        ("Sapphire Foods India", "SAPPHIRE.NS"),
        ("Saregama India", "SAREGAMA.NS"),
        ("Shemaroo Entertainment", "SHEMAROO.NS"),
        ("Sula Vineyards", "SULA.NS"),
        ("Sun TV Network", "SUNTV.NS"),
        ("Suryoday Small Finance Bank", "SURYODAY.NS"),
        ("Swiggy", "SWIGGY.NS"),
        ("TBO Tek", "TBOTEK.NS"),
        ("TV Today Network", "TVTODAY.NS"),
        ("TV18 Broadcast", "TV18BRDCST.NS"),
        ("Tata Teleservices (Maharashtra)", "TTML.NS"),
        ("Ujjivan Small Finance Bank", "UJJIVANSFB.NS"),
        ("Unicommerce eSolutions", "UNICOMMERCE.NS"),
        ("Utkarsh Small Finance Bank", "UTKARSHBNK.NS"),
        ("Ventive Hospitality", "VENTIVE.NS"),
        ("Vishal Mega Mart", "VMM.NS"),
        ("Vodafone Idea", "IDEA.NS"),
        ("Westlife Foodworld", "WESTLIFE.NS"),
        ("Zee Entertainment Enterprises", "ZEEL.NS"),
        ("Zomato", "ZOMATO.NS"),
    ],
    "Pharma & Healthcare": [
        ("ASK Automotive (unrelated, auto ancillary)", "ASKAUTOLTD.NS"),
        ("Abbott India", "ABBOTINDIA.NS"),
        ("Ajanta Pharma", "AJANTPHARM.NS"),
        ("Akums Drugs and Pharmaceuticals", "AKUMS.NS"),
        ("Alkem Laboratories", "ALKEM.NS"),
        ("Apollo Hospitals Enterprise", "APOLLOHOSP.NS"),
        ("Aster DM Healthcare", "ASTERDM.NS"),
        ("Aurobindo Pharma", "AUROPHARMA.NS"),
        ("Biocon", "BIOCON.NS"),
        ("Blue Jet Healthcare", "BLUEJET.NS"),
        ("Cadila Healthcare (Zydus Lifesciences)", "ZYDUSLIFE.NS"),
        ("Caplin Point Laboratories", "CAPLIPOINT.NS"),
        ("Cipla", "CIPLA.NS"),
        ("Divis Laboratories", "DIVISLAB.NS"),
        ("Dr Lal PathLabs", "LALPATHLAB.NS"),
        ("Dr Reddys Laboratories", "DRREDDY.NS"),
        ("Emcure Pharmaceuticals", "EMCURE.NS"),
        ("Eris Lifesciences", "ERIS.NS"),
        ("FDC", "FDC.NS"),
        ("Fortis Healthcare", "FORTIS.NS"),
        ("Gland Pharma", "GLAND.NS"),
        ("GlaxoSmithKline Pharmaceuticals", "GLAXO.NS"),
        ("Glenmark Pharmaceuticals", "GLENMARK.NS"),
        ("Global Health (Medanta)", "MEDANTA.NS"),
        ("Granules India", "GRANULES.NS"),
        ("Indoco Remedies", "INDOCO.NS"),
        ("Ipca Laboratories", "IPCALAB.NS"),
        ("J B Chemicals & Pharmaceuticals", "JBCHEPHARM.NS"),
        ("Jubilant Ingrevia", "JUBLINGREA.NS"),
        ("Jubilant Pharmova", "JUBLPHARMA.NS"),
        ("Krishna Institute of Medical Sciences", "KIMS.NS"),
        ("Laurus Labs", "LAURUSLABS.NS"),
        ("Lupin", "LUPIN.NS"),
        ("Mankind Pharma", "MANKIND.NS"),
        ("Marksans Pharma", "MARKSANS.NS"),
        ("Max Healthcare Institute", "MAXHEALTH.NS"),
        ("Metropolis Healthcare", "METROPOLIS.NS"),
        ("Narayana Hrudayalaya", "NH.NS"),
        ("Natco Pharma", "NATCOPHARM.NS"),
        ("Pfizer India", "PFIZER.NS"),
        ("Piramal Pharma", "PPLPHARMA.NS"),
        ("Poly Medicure", "POLYMED.NS"),
        ("Rainbow Children's Medicare", "RAINBOW.NS"),
        ("Sanofi India", "SANOFI.NS"),
        ("Sequent Scientific", "SEQUENT.NS"),
        ("Shalby", "SHALBY.NS"),
        ("Strides Pharma Science", "STAR.NS"),
        ("Sun Pharma Advanced Research", "SPARC.NS"),
        ("Sun Pharmaceutical Industries", "SUNPHARMA.NS"),
        ("Suven Pharmaceuticals", "SUVENPHAR.NS"),
        ("Syngene International", "SYNGENE.NS"),
        ("Thyrocare Technologies", "THYROCARE.NS"),
        ("Torrent Pharmaceuticals", "TORNTPHARM.NS"),
        ("Vijaya Diagnostic Centre", "VIJAYA.NS"),
        ("Windlas Biotech", "WINDLAS.NS"),
        ("Wockhardt", "WOCKPHARMA.NS"),
    ],
    "Services & Others": [
        ("3i Infotech", "3IINFOTECH.NS"),
        ("Adlabs Entertainment", "ADLABS.NS"),
        ("Ador Welding", "ADORWELD.NS"),
        ("Aptech", "APTECHT.NS"),
        ("Archidply Industries", "ARCHIDPLY.NS"),
        ("Bharat Bijlee", "BBL.NS"),
        ("Birlasoft", "BSOFT.NS"),
        ("CIEL HR Services", "CIEL.NS"),
        ("Career Point", "CAREERP.NS"),
        ("Cigniti Technologies", "CIGNITITEC.NS"),
        ("Cox & Kings (legacy)", "COXANDKING.NS"),
        ("Datamatics Global Services", "DATAMATICS.NS"),
        ("Delta Corp", "DELTACORP.NS"),
        ("Elecon Engineering Company", "ELECON.NS"),
        ("Esab India", "ESABINDIA.NS"),
        ("GE Power India", "GEPIL.NS"),
        ("GMM Pfaudler", "GMMPFAUDLR.NS"),
        ("Greenlam Industries", "GREENLAM.NS"),
        ("HSIL (Hindware)", "HSIL.NS"),
        ("Info Edge India (Naukri)", "NAUKRI.NS"),
        ("Inox Wind Energy", "INOXGREEN.NS"),
        ("KSB", "KSB.NS"),
        ("Kirloskar Ferrous Industries", "KIRLFER.NS"),
        ("Kirloskar Industries", "KIRLOSIND.NS"),
        ("Majesco (legacy)", "MAJESCO.NS"),
        ("Mastek", "MASTEK.NS"),
        ("NIIT", "NIIT.NS"),
        ("NIIT Learning Systems", "NIITLTD.NS"),
        ("Nucleus Software Exports", "NUCLEUS.NS"),
        ("Onmobile Global", "ONMOBILE.NS"),
        ("Orient Bell", "ORIENTBELL.NS"),
        ("Polaris Consulting (legacy, now Virtusa placeholder)", "VIRTUSA.NS"),
        ("Quess Corp", "QUESS.NS"),
        ("R Systems International", "RSYSTEMS.NS"),
        ("Ramco Systems", "RAMCOSYS.NS"),
        ("Rategain Travel Technologies", "RATEGAIN.NS"),
        ("Royal Orchid Hotels", "ROHLTD.NS"),
        ("Sasken Technologies", "SASKEN.NS"),
        ("Shakti Pumps (India)", "SHAKTIPUMP.NS"),
        ("Somany Ceramics", "SOMANYCERA.NS"),
        ("Spencer's Retail", "SPENCERS.NS"),
        ("Subex", "SUBEXLTD.NS"),
        ("TCI Express", "TCIEXP.NS"),
        ("TD Power Systems", "TDPOWERSYS.NS"),
        ("Taj GVK Hotels & Resorts", "TAJGVK.NS"),
        ("Team Lease Services", "TEAMLEASE.NS"),
        ("Thomas Cook (India)", "THOMASCOOK.NS"),
        ("Trent", "TRENT.NS"),
        ("WPIL", "WPIL.NS"),
        ("Wonderla Holidays", "WONDERLA.NS"),
        ("Xchanging Solutions (legacy)", "XCHANGING.NS"),
        ("Yatra Online", "YATRA.NS"),
        ("Zaggle Prepaid Ocean Services", "ZAGGLE.NS"),
        ("eClerx Services", "ECLERX.NS"),
        ("eMudhra", "EMUDHRA.NS"),
    ],
    "Cement & Building Materials": [
        ("ACC", "ACC.NS"),
        ("AGI Greenpac (HSIL renamed)", "AGI.NS"),
        ("Ambuja Cements", "AMBUJACEM.NS"),
        ("Andhra Paper", "ANDHRAPAP.NS"),
        ("Asian Granito India", "ASIANTILES.NS"),
        ("Barak Valley Cements", "BARAKVALLEY.NS"),
        ("Birla Corporation", "BIRLACORPN.NS"),
        ("Borosil", "BOROSIL.NS"),
        ("Century Plyboards India", "CENTURYPLY.NS"),
        ("Century Textiles and Industries", "CENTURYTEX.NS"),
        ("Cera Sanitaryware", "CERA.NS"),
        ("Cosmo First", "COSMOFIRST.NS"),
        ("Dalmia Bharat", "DALBHARAT.NS"),
        ("Deccan Cements", "DECCANCE.NS"),
        ("EPL Limited (Essel Propack)", "EPL.NS"),
        ("Emami Paper Mills", "EMAMIPAP.NS"),
        ("Everest Industries", "EVERESTIND.NS"),
        ("Grasim Industries", "GRASIM.NS"),
        ("Greenpanel Industries", "GREENPANEL.NS"),
        ("HIL Limited", "HIL.NS"),
        ("Heidelberg Cement India", "HEIDELBERG.NS"),
        ("Huhtamaki India", "HUHTAMAKI.NS"),
        ("India Cements", "INDIACEM.NS"),
        ("JK Cement", "JKCEMENT.NS"),
        ("JK Paper", "JKPAPER.NS"),
        ("Jindal Poly Films", "JINDALPOLY.NS"),
        ("KCP", "KCP.NS"),
        ("Kajaria Ceramics", "KAJARIACER.NS"),
        ("Mangalam Cement", "MANGLMCEM.NS"),
        ("Mold-Tek Packaging", "MOLDTKPAC.NS"),
        ("NCL Industries", "NCLIND.NS"),
        ("Nitco", "NITCO.NS"),
        ("Orient Cement", "ORIENTCEM.NS"),
        ("Orient Paper & Industries", "ORIENTPPR.NS"),
        ("Panyam Cements", "PANYAMCEM.NS"),
        ("Pokarna", "POKARNA.NS"),
        ("Polyplex Corporation", "POLYPLEX.NS"),
        ("Prism Johnson", "PRSMJOHNSN.NS"),
        ("Ramco Industries", "RAMCOIND.NS"),
        ("Sagar Cements", "SAGCEM.NS"),
        ("Seshasayee Paper and Boards", "SESHAPAPER.NS"),
        ("Shree Cement", "SHREECEM.NS"),
        ("Star Cement", "STARCEMENT.NS"),
        ("TCPL Packaging", "TCPLPACK.NS"),
        ("Tamil Nadu Newsprint and Papers", "TNPL.NS"),
        ("The Ramco Cements", "RAMCOCEM.NS"),
        ("Time Technoplast", "TIMETECHNO.NS"),
        ("Udaipur Cement Works", "UDAICEMENT.NS"),
        ("Uflex", "UFLEX.NS"),
        ("UltraTech Cement", "ULTRACEMCO.NS"),
        ("Visaka Industries", "VISAKAIND.NS"),
        ("West Coast Paper Mills", "WSTCSTPAPR.NS"),
    ],
    "Auto & Auto Ancillaries": [
        ("Amara Raja Energy & Mobility", "ARE&M.NS"),
        ("Apollo Tyres", "APOLLOTYRE.NS"),
        ("Ashok Leyland", "ASHOKLEY.NS"),
        ("Ather Energy", "ATHERENERG.NS"),
        ("Bajaj Auto", "BAJAJ-AUTO.NS"),
        ("Balkrishna Industries", "BALKRISIND.NS"),
        ("Banco Products (India)", "BANCOINDIA.NS"),
        ("Bharat Forge", "BHARATFORG.NS"),
        ("Bharat Gears", "BHARATGEAR.NS"),
        ("Bosch", "BOSCHLTD.NS"),
        ("CEAT", "CEATLTD.NS"),
        ("Craftsman Automation", "CRAFTSMAN.NS"),
        ("DCM Shriram Industries", "DCMSRIND.NS"),
        ("Eicher Motors", "EICHERMOT.NS"),
        ("Endurance Technologies", "ENDURANCE.NS"),
        ("Escorts Kubota", "ESCORTS.NS"),
        ("Exide Industries", "EXIDEIND.NS"),
        ("Force Motors", "FORCEMOT.NS"),
        ("HBL Power Systems", "HBLPOWER.NS"),
        ("Hero MotoCorp", "HEROMOTOCO.NS"),
        ("JBM Auto", "JBMA.NS"),
        ("JK Tyre & Industries", "JKTYRE.NS"),
        ("Lumax Industries", "LUMAXIND.NS"),
        ("MRF", "MRF.NS"),
        ("Mahindra & Mahindra", "M&M.NS"),
        ("Mahindra CIE Automotive", "MAHINDCIE.NS"),
        ("Maruti Suzuki India", "MARUTI.NS"),
        ("Minda Corporation", "MINDACORP.NS"),
        ("Motherson Sumi Wiring India", "MSUMI.NS"),
        ("Munjal Auto Industries", "MUNJALAU.NS"),
        ("Munjal Showa", "MUNJALSHOW.NS"),
        ("Olectra Greentech", "OLECTRA.NS"),
        ("PPAP Automotive", "PPAP.NS"),
        ("Precision Camshafts", "PRECAM.NS"),
        ("Rane Brake Lining", "RML.NS"),
        ("Rane Engine Valve", "RANEENGINE.NS"),
        ("Rane Holdings", "RANEHOLDIN.NS"),
        ("Rico Auto Industries", "RICOAUTO.NS"),
        ("SML Isuzu", "SMLISUZU.NS"),
        ("Shivam Autotech", "SHIVAMAUTO.NS"),
        ("Sona BLW Precision Forgings", "SONACOMS.NS"),
        ("Subros", "SUBROS.NS"),
        ("TVS Motor Company", "TVSMOTOR.NS"),
        ("Tata Motors", "TATAMOTORS.NS"),
        ("Tata Motors DVR (legacy)", "TATAMTRDVR.NS"),
        ("Tube Investments of India", "TIINDIA.NS"),
        ("Uno Minda", "UNOMINDA.NS"),
        ("Varroc Engineering", "VARROC.NS"),
    ],
    "Real Estate & Infrastructure": [
        ("Adani Ports and SEZ", "ADANIPORTS.NS"),
        ("Adani Total Gas", "ATGL.NS"),
        ("Ajmera Realty & Infra India", "AJMERA.NS"),
        ("Anant Raj", "ANANTRAJ.NS"),
        ("Arvind SmartSpaces", "ARVSMART.NS"),
        ("Ashiana Housing", "ASHIANA.NS"),
        ("Ashoka Buildcon", "ASHOKA.NS"),
        ("Brigade Enterprises", "BRIGADE.NS"),
        ("DLF", "DLF.NS"),
        ("Dilip Buildcon", "DBL.NS"),
        ("GMR Airports Infrastructure", "GMRINFRA.NS"),
        ("GR Infraprojects", "GRINFRA.NS"),
        ("GVK Power & Infrastructure", "GVKPIL.NS"),
        ("Genus Power Infrastructures", "GENUSPOWER.NS"),
        ("Godrej Properties", "GODREJPROP.NS"),
        ("Gujarat Pipavav Port", "GPPL.NS"),
        ("HG Infra Engineering", "HGINFRA.NS"),
        ("HPL Electric & Power", "HPL.NS"),
        ("IRB Infrastructure Developers", "IRB.NS"),
        ("Indiabulls Real Estate (Embassy Developments)", "EMBASSY.NS"),
        ("J Kumar Infraprojects", "JKIL.NS"),
        ("JSW Infrastructure", "JSWINFRA.NS"),
        ("KEC International", "KEC.NS"),
        ("KNR Constructions", "KNRCON.NS"),
        ("Kalpataru Projects International", "KPIL.NS"),
        ("Keystone Realtors (Rustomjee)", "RUSTOMJEE.NS"),
        ("Kolte-Patil Developers", "KOLTEPATIL.NS"),
        ("Macrotech Developers (Lodha)", "LODHA.NS"),
        ("Mahindra Lifespace Developers", "MAHLIFE.NS"),
        ("Man Infraconstruction", "MANINFRA.NS"),
        ("Nagarjuna Construction Company (NCC)", "NCC.NS"),
        ("Navkar Corporation", "NAVKARCORP.NS"),
        ("Nirlon", "NIRLON.NS"),
        ("Oberoi Realty", "OBEROIRLTY.NS"),
        ("PNC Infratech", "PNCINFRA.NS"),
        ("Phoenix Mills", "PHOENIXLTD.NS"),
        ("Prestige Estates Projects", "PRESTIGE.NS"),
        ("Puravankara", "PURVA.NS"),
        ("Sadbhav Engineering", "SADBHAV.NS"),
        ("Sadbhav Infrastructure Project", "SADBHIN.NS"),
        ("Signature Global (India)", "SIGNATURE.NS"),
        ("Skipper", "SKIPPER.NS"),
        ("Sobha", "SOBHA.NS"),
        ("Sunteck Realty", "SUNTECK.NS"),
        ("Suraj Estate Developers", "SURAJEST.NS"),
        ("Techno Electric & Engineering", "TECHNOE.NS"),
        ("Transformers and Rectifiers India", "TARIL.NS"),
        ("Voltamp Transformers", "VOLTAMP.NS"),
    ],
    "Chemicals & Fertilizers": [
        ("Aarti Industries", "AARTIIND.NS"),
        ("Aarti Pharmalabs", "AARTIPHARM.NS"),
        ("Aether Industries", "AETHER.NS"),
        ("Alkyl Amines Chemicals", "ALKYLAMINE.NS"),
        ("Ami Organics", "AMIORG.NS"),
        ("Atul", "ATUL.NS"),
        ("Balaji Amines", "BALAMINES.NS"),
        ("Bayer CropScience (India)", "BAYERCROP.NS"),
        ("Chambal Fertilisers and Chemicals", "CHAMBLFERT.NS"),
        ("Chemplast Sanmar", "CHEMPLASTS.NS"),
        ("Clean Science and Technology", "CLEAN.NS"),
        ("Coromandel International", "COROMANDEL.NS"),
        ("DCW", "DCW.NS"),
        ("Deepak Chemtex", "DEEPCHEM.NS"),
        ("Deepak Nitrite", "DEEPAKNTR.NS"),
        ("Fine Organic Industries", "FINEORG.NS"),
        ("GNFC (Gujarat Narmada Valley Fertilizers)", "GNFC.NS"),
        ("Godavari Biorefineries", "GODAVARIB.NS"),
        ("Gujarat Alkalies and Chemicals", "GUJALKALI.NS"),
        ("Gujarat Fluorochemicals", "FLUOROCHEM.NS"),
        ("Gujarat State Fertilizers & Chemicals", "GSFC.NS"),
        ("India Glycols", "INDIAGLYCO.NS"),
        ("Linde India", "LINDEINDIA.NS"),
        ("Nagarjuna Fertilizers and Chemicals", "NAGARFERT.NS"),
        ("Navin Fluorine International", "NAVINFLUOR.NS"),
        ("PI Industries", "PIIND.NS"),
        ("Paushak", "PAUSHAKLTD.NS"),
        ("Pidilite Industries", "PIDILITIND.NS"),
        ("Rallis India", "RALLIS.NS"),
        ("Rashtriya Chemicals & Fertilizers", "RCF.NS"),
        ("Rossari Biotech", "ROSSARI.NS"),
        ("SRF", "SRF.NS"),
        ("Solar Industries India", "SOLARINDS.NS"),
        ("Sumitomo Chemical India", "SUMICHEM.NS"),
        ("Tata Chemicals", "TATACHEM.NS"),
        ("UPL", "UPL.NS"),
        ("Vinati Organics", "VINATIORGA.NS"),
        ("Vishnu Chemicals", "VISHNU.NS"),
        ("Yasho Industries", "YASHO.NS"),
    ],
    "IT & Technology": [
        ("Affle India", "AFFLE.NS"),
        ("Coforge", "COFORGE.NS"),
        ("Cyient", "CYIENT.NS"),
        ("D-Link India", "DLINKINDIA.NS"),
        ("Firstsource Solutions", "FSL.NS"),
        ("GTPL Hathway", "GTPL.NS"),
        ("Genesys International", "GENESYS.NS"),
        ("HCL Technologies", "HCLTECH.NS"),
        ("HFCL", "HFCL.NS"),
        ("Happiest Minds Technologies", "HAPPSTMNDS.NS"),
        ("Infosys", "INFY.NS"),
        ("Intellect Design Arena", "INTELLECT.NS"),
        ("KPIT Technologies", "KPITTECH.NS"),
        ("L&T Technology Services", "LTTS.NS"),
        ("LTIMindtree", "LTIM.NS"),
        ("Larsen & Toubro Infotech (legacy)", "LTI.NS"),
        ("Latent View Analytics", "LATENTVIEW.NS"),
        ("Mindtree (legacy, merged into LTIM)", "MINDTREE.NS"),
        ("Mphasis", "MPHASIS.NS"),
        ("Netweb Technologies India", "NETWEB.NS"),
        ("Newgen Software Technologies", "NEWGEN.NS"),
        ("Onward Technologies", "ONWARDTEC.NS"),
        ("Oracle Financial Services Software", "OFSS.NS"),
        ("Persistent Systems", "PERSISTENT.NS"),
        ("Rail Tel Corporation of India", "RAILTEL.NS"),
        ("Route Mobile", "ROUTE.NS"),
        ("Sify Technologies", "SIFY.NS"),
        ("Sonata Software", "SONATSOFTW.NS"),
        ("Sterlite Technologies", "STLTECH.NS"),
        ("Tata Communications", "TATACOMM.NS"),
        ("Tata Consultancy Services", "TCS.NS"),
        ("Tata Elxsi", "TATAELXSI.NS"),
        ("Tata Technologies", "TATATECH.NS"),
        ("Tech Mahindra", "TECHM.NS"),
        ("Tejas Networks", "TEJASNET.NS"),
        ("Vindhya Telelinks", "VINDHYATEL.NS"),
        ("Wipro", "WIPRO.NS"),
        ("Zensar Technologies", "ZENSARTECH.NS"),
    ],
    "Agriculture & Agro-Processing": [
        ("Adani Wilmar", "AWL.NS"),
        ("Agro Tech Foods", "ATFL.NS"),
        ("Bajaj Hindusthan Sugar", "BAJAJHIND.NS"),
        ("Balrampur Chini Mills", "BALRAMCHIN.NS"),
        ("Best Agrolife", "BESTAGRO.NS"),
        ("Bharat Rasayan", "BHARATRAS.NS"),
        ("Bombay Burmah Trading Corporation", "BBTC.NS"),
        ("Britannia Industries", "BRITANNIA.NS"),
        ("DFM Foods", "DFMFOODS.NS"),
        ("Dhampur Sugar Mills", "DHAMPURSUG.NS"),
        ("Dhanuka Agritech", "DHANUKA.NS"),
        ("EID Parry (India)", "EIDPARRY.NS"),
        ("Excel Industries", "EXCELINDUS.NS"),
        ("Godrej Agrovet", "GODREJAGRO.NS"),
        ("Gujarat Ambuja Exports", "GAEL.NS"),
        ("Harrisons Malayalam", "HARRMALAYA.NS"),
        ("Hatsun Agro Product", "HATSUN.NS"),
        ("Heranba Industries", "HERANBA.NS"),
        ("Heritage Foods", "HERITGFOOD.NS"),
        ("Insecticides India", "INSECTICID.NS"),
        ("KRBL", "KRBL.NS"),
        ("Kaveri Seed Company", "KSCL.NS"),
        ("Kohinoor Foods", "KOHINOOR.NS"),
        ("Kwality", "KWALITY.NS"),
        ("LT Foods (Daawat Rice)", "LTFOODS.NS"),
        ("Mangalam Seeds", "MSPL.NS"),
        ("McLeod Russel India", "MCLEODRUSS.NS"),
        ("Parag Milk Foods", "PARAGMILK.NS"),
        ("Prataap Snacks", "DIAMONDYD.NS"),
        ("Punjab Chemicals and Crop Protection", "PUNJABCHEM.NS"),
        ("Rossell India", "ROSSELLIND.NS"),
        ("Ruchi Soya (Patanjali Foods)", "PATANJALI.NS"),
        ("Sharda Cropchem", "SHARDACROP.NS"),
        ("Tata Coffee (legacy)", "TATACOFFEE.NS"),
        ("Triveni Engineering & Industries", "TRIVENI.NS"),
        ("Usher Agro", "USHERAGRO.NS"),
        ("Vadilal Industries", "VADILALIND.NS"),
    ],
    "Banking": [
        ("AU Small Finance Bank", "AUBANK.NS"),
        ("Axis Bank", "AXISBANK.NS"),
        ("Bandhan Bank", "BANDHANBNK.NS"),
        ("Bank of Baroda", "BANKBARODA.NS"),
        ("Bank of India", "BANKINDIA.NS"),
        ("Bank of Maharashtra", "MAHABANK.NS"),
        ("CSB Bank", "CSBBANK.NS"),
        ("Canara Bank", "CANBK.NS"),
        ("Central Bank of India", "CENTRALBK.NS"),
        ("City Union Bank", "CUB.NS"),
        ("DCB Bank", "DCBBANK.NS"),
        ("Dhanlaxmi Bank", "DHANBANK.NS"),
        ("Equitas Small Finance Bank", "EQUITASBNK.NS"),
        ("Federal Bank", "FEDERALBNK.NS"),
        ("HDFC Bank", "HDFCBANK.NS"),
        ("ICICI Bank", "ICICIBANK.NS"),
        ("IDBI Bank", "IDBI.NS"),
        ("IDFC First Bank", "IDFCFIRSTB.NS"),
        ("Indian Bank", "INDIANB.NS"),
        ("Indian Overseas Bank", "IOB.NS"),
        ("IndusInd Bank", "INDUSINDBK.NS"),
        ("Jammu & Kashmir Bank", "J&KBANK.NS"),
        ("Karnataka Bank", "KTKBANK.NS"),
        ("Karur Vysya Bank", "KARURVYSYA.NS"),
        ("Kotak Mahindra Bank", "KOTAKBANK.NS"),
        ("Punjab & Sind Bank", "PSB.NS"),
        ("Punjab National Bank", "PNB.NS"),
        ("RBL Bank", "RBLBANK.NS"),
        ("South Indian Bank", "SOUTHBANK.NS"),
        ("State Bank of India", "SBIN.NS"),
        ("Tamilnad Mercantile Bank", "TMB.NS"),
        ("UCO Bank", "UCOBANK.NS"),
        ("Union Bank of India", "UNIONBANK.NS"),
        ("Yes Bank", "YESBANK.NS"),
    ],
    "Metals & Mining": [
        ("APL Apollo Tubes", "APLAPOLLO.NS"),
        ("Adhunik Metaliks (legacy)", "ADHUNIK.NS"),
        ("Coal India", "COALINDIA.NS"),
        ("Electrosteel Castings", "ELECTCAST.NS"),
        ("Godawari Power & Ispat", "GPIL.NS"),
        ("Hindalco Industries", "HINDALCO.NS"),
        ("Hindustan Copper", "HINDCOPPER.NS"),
        ("Hindustan Zinc", "HINDZINC.NS"),
        ("JSW Steel", "JSWSTEEL.NS"),
        ("Jai Balaji Industries", "JAIBALAJI.NS"),
        ("Jindal Saw", "JINDALSAW.NS"),
        ("Jindal Stainless", "JSL.NS"),
        ("Jindal Steel & Power", "JINDALSTEL.NS"),
        ("Kalyani Steels", "KSL.NS"),
        ("MOIL", "MOIL.NS"),
        ("Maharashtra Seamless", "MAHSEAMLES.NS"),
        ("Man Industries (India)", "MANINDS.NS"),
        ("National Aluminium Company", "NATIONALUM.NS"),
        ("National Mineral Development Corp", "NMDC.NS"),
        ("Prakash Industries", "PRAKASH.NS"),
        ("Ratnamani Metals and Tubes", "RATNAMANI.NS"),
        ("Sarda Energy & Minerals", "SARDAEN.NS"),
        ("Shyam Metalics and Energy", "SHYAMMETL.NS"),
        ("Surya Roshni", "SURYAROSNI.NS"),
        ("Tata Steel", "TATASTEEL.NS"),
        ("Usha Martin", "USHAMART.NS"),
        ("Vedanta", "VEDL.NS"),
        ("Welspun Corp", "WELCORP.NS"),
    ],
    "Renewable & Power": [
        ("Adani Energy Solutions", "ADANIENSOL.NS"),
        ("Adani Green Energy", "ADANIGREEN.NS"),
        ("Adani Power", "ADANIPOWER.NS"),
        ("Borosil Renewables", "BORORENEW.NS"),
        ("CESC", "CESC.NS"),
        ("Gensol Engineering", "GENSOL.NS"),
        ("Indowind Energy", "INDOWIND.NS"),
        ("Inox Wind", "INOXWIND.NS"),
        ("Insolation Energy", "INSOLATION.NS"),
        ("JSW Energy", "JSWENERGY.NS"),
        ("KPI Green Energy", "KPIGREEN.NS"),
        ("NHPC", "NHPC.NS"),
        ("NTPC", "NTPC.NS"),
        ("NTPC Green Energy", "NTPCGREEN.NS"),
        ("Orient Green Power", "GREENPOWER.NS"),
        ("Power Grid Corporation of India", "POWERGRID.NS"),
        ("Premier Energies", "PREMIERENE.NS"),
        ("Reliance Power", "RPOWER.NS"),
        ("SJVN", "SJVN.NS"),
        ("Servotech Renewable Power System", "SERVOTECH.NS"),
        ("Sterling and Wilson Renewable Energy", "SWSOLAR.NS"),
        ("Suzlon Energy", "SUZLON.NS"),
        ("Tata Power Company", "TATAPOWER.NS"),
        ("Torrent Power", "TORNTPOWER.NS"),
        ("Urja Global", "URJA.NS"),
        ("Waaree Energies", "WAAREEENER.NS"),
        ("Websol Energy System", "WEBELSOLAR.NS"),
    ],
    "PSU & Government-owned": [
        ("Andrew Yule & Company", "ANDREWYU.NS"),
        ("Balmer Lawrie & Company", "BALMLAWRIE.NS"),
        ("Bharat Immunologicals and Biologicals Corp", "BIBCL.NS"),
        ("Bharat Petroleum Corporation", "BPCL.NS"),
        ("Container Corporation of India", "CONCOR.NS"),
        ("Fertilizers and Chemicals Travancore (FACT)", "FACT.NS"),
        ("GAIL Gas", "GAILGAS.NS"),
        ("HMT", "HMT.NS"),
        ("Housing and Urban Development Corp (HUDCO)", "HUDCO.NS"),
        ("IFCI", "IFCI.NS"),
        ("ITI Limited", "ITI.NS"),
        ("Indian Renewable Energy Development Agency (IREDA)", "IREDA.NS"),
        ("Kudremukh Iron Ore Company", "KIOCL.NS"),
        ("MMTC", "MMTC.NS"),
        ("MSTC", "MSTCLTD.NS"),
        ("Madras Fertilizers", "MADRASFERT.NS"),
        ("Mahanagar Gas", "MGL.NS"),
        ("Manaksia", "MANAKSIA.NS"),
        ("National Fertilizers", "NFL.NS"),
        ("Neyveli Lignite Corporation (NLC India)", "NLCINDIA.NS"),
        ("PTC India", "PTC.NS"),
        ("Power Finance Corporation", "PFC.NS"),
        ("SAIL (Steel Authority of India)", "SAIL.NS"),
        ("State Trading Corporation of India", "STCINDIA.NS"),
    ],
    "Diversified Large Cap": [
        ("3M India", "3MINDIA.NS"),
        ("Adani Enterprises", "ADANIENT.NS"),
        ("Adani Transmission", "ADANITRANS.NS"),
        ("Castrol India", "CASTROLIND.NS"),
        ("DCM Shriram", "DCMSHRIRAM.NS"),
        ("Future Consumer", "FCONSUMER.NS"),
        ("Future Retail", "FRETAIL.NS"),
        ("Godrej Industries", "GODREJIND.NS"),
        ("Gulf Oil Lubricants India", "GULFOILLUB.NS"),
        ("JSW Holdings", "JSWHL.NS"),
        ("Kesoram Industries", "KESORAMIND.NS"),
        ("Panama Petrochem", "PANAMAPET.NS"),
        ("Reliance Industries", "RELIANCE.NS"),
        ("Reliance Infrastructure", "RELINFRA.NS"),
        ("Samvardhana Motherson International", "MOTHERSON.NS"),
        ("Savita Oil Technologies", "SOTL.NS"),
        ("Siemens", "SIEMENS.NS"),
        ("Williamson Magor & Company", "WILLAMAGOR.NS"),
    ],
    "Oil, Gas & Energy": [
        ("Aegis Logistics", "AEGISCHEM.NS"),
        ("Chennai Petroleum Corporation", "CHENNPETRO.NS"),
        ("GAIL India", "GAIL.NS"),
        ("Gujarat Gas", "GUJGASLTD.NS"),
        ("Gujarat State Petronet", "GSPL.NS"),
        ("Hindustan Petroleum Corporation", "HINDPETRO.NS"),
        ("Indian Oil Corporation", "IOC.NS"),
        ("Indraprastha Gas", "IGL.NS"),
        ("Mangalore Refinery and Petrochemicals", "MRPL.NS"),
        ("Oil India", "OIL.NS"),
        ("Oil and Natural Gas Corporation", "ONGC.NS"),
        ("Petronet LNG", "PETRONET.NS"),
    ],
    "Defense & Aerospace": [
        ("Apollo Micro Systems", "APOLLO.NS"),
        ("Astra Microwave Products", "ASTRAMICRO.NS"),
        ("Azad Engineering", "AZAD.NS"),
        ("Bharat Electronics", "BEL.NS"),
        ("DCX Systems", "DCXINDIA.NS"),
        ("Data Patterns (India)", "DATAPATTNS.NS"),
        ("Hindustan Aeronautics", "HAL.NS"),
        ("MTAR Technologies", "MTARTECH.NS"),
        ("Paras Defence and Space Technologies", "PARAS.NS"),
        ("Premier Explosives", "PREMEXPLN.NS"),
        ("Zen Technologies", "ZENTEC.NS"),
    ],
    "Logistics & Transportation": [
        ("Allcargo Logistics", "ALLCARGO.NS"),
        ("Blue Dart Express", "BLUEDART.NS"),
        ("Gateway Distriparks", "GATEWAY.NS"),
        ("Great Eastern Shipping Company", "GESHIP.NS"),
        ("Indian Railway Catering and Tourism Corp", "IRCTC.NS"),
        ("Interglobe Aviation (IndiGo)", "INDIGO.NS"),
        ("Mahindra Logistics", "MAHLOG.NS"),
        ("Shipping Corporation of India", "SCI.NS"),
        ("SpiceJet", "SPICEJET.NS"),
        ("TCI (Transport Corporation of India)", "TCI.NS"),
        ("VRL Logistics", "VRLLOG.NS"),
    ],
    "Textiles & Apparel": [
        ("Arvind", "ARVIND.NS"),
        ("Gokaldas Exports", "GOKEX.NS"),
        ("KPR Mill", "KPRMILL.NS"),
        ("Page Industries", "PAGEIND.NS"),
        ("Raymond", "RAYMOND.NS"),
        ("SP Apparels", "SPAL.NS"),
        ("Siyaram Silk Mills", "SIYSIL.NS"),
        ("Trident", "TRIDENT.NS"),
        ("Vardhman Textiles", "VTL.NS"),
        ("Welspun Living", "WELSPUNLIV.NS"),
    ],
}


# Flat ticker -> category lookup, derived from CATEGORIES above.
SECTOR_OF = {ticker: cat for cat, items in CATEGORIES.items() for _, ticker in items}


def category_of(ticker: str) -> str:
    """Return the category for a ticker, or "Uncategorized" if unknown."""
    return SECTOR_OF.get(ticker, "Uncategorized")
