"""
companies.py
------------
Database of Indian companies and their NSE ticker symbols (Yahoo Finance format,
i.e. with the ".NS" suffix). Import COMPANIES into the main script.

HOW TO ADD MORE COMPANIES
--------------------------
Just add more entries to the COMPANIES dict below, in the form:

    "Company Display Name": "TICKER.NS",

Find the correct ticker by searching the company on https://finance.yahoo.com
or https://www.nseindia.com — use the NSE symbol and append ".NS".
(If a stock is only listed on BSE, use ".BO" instead of ".NS".)

Tip: keys are case-insensitive when looked up via the CLI (see main.py),
so you don't need to worry about exact casing when searching.
"""

COMPANIES = {
    # ---------------- NIFTY 50 / Large cap ----------------
    "Reliance Industries": "RELIANCE.NS",
    "Tata Consultancy Services": "TCS.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "Infosys": "INFY.NS",
    "State Bank of India": "SBIN.NS",
    "Hindustan Unilever": "HINDUNILVR.NS",
    "Bharti Airtel": "BHARTIARTL.NS",
    "ITC": "ITC.NS",
    "Kotak Mahindra Bank": "KOTAKBANK.NS",
    "Larsen & Toubro": "LT.NS",
    "Axis Bank": "AXISBANK.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "Maruti Suzuki India": "MARUTI.NS",
    "Titan Company": "TITAN.NS",
    "Sun Pharmaceutical Industries": "SUNPHARMA.NS",
    "UltraTech Cement": "ULTRACEMCO.NS",
    "Wipro": "WIPRO.NS",
    "Nestle India": "NESTLEIND.NS",
    "HCL Technologies": "HCLTECH.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "Tata Steel": "TATASTEEL.NS",
    "Power Grid Corporation of India": "POWERGRID.NS",
    "NTPC": "NTPC.NS",
    "Mahindra & Mahindra": "M&M.NS",
    "Bajaj Finserv": "BAJAJFINSV.NS",
    "IndusInd Bank": "INDUSINDBK.NS",
    "JSW Steel": "JSWSTEEL.NS",
    "Grasim Industries": "GRASIM.NS",
    "Adani Enterprises": "ADANIENT.NS",
    "Adani Ports and SEZ": "ADANIPORTS.NS",
    "Coal India": "COALINDIA.NS",
    "Bajaj Auto": "BAJAJ-AUTO.NS",
    "Tech Mahindra": "TECHM.NS",
    "Hindalco Industries": "HINDALCO.NS",
    "Dr Reddys Laboratories": "DRREDDY.NS",
    "Cipla": "CIPLA.NS",
    "Britannia Industries": "BRITANNIA.NS",
    "Eicher Motors": "EICHERMOT.NS",
    "Apollo Hospitals Enterprise": "APOLLOHOSP.NS",
    "Divis Laboratories": "DIVISLAB.NS",
    "Shree Cement": "SHREECEM.NS",
    "SBI Life Insurance": "SBILIFE.NS",
    "HDFC Life Insurance": "HDFCLIFE.NS",
    "Hero MotoCorp": "HEROMOTOCO.NS",
    "Oil and Natural Gas Corporation": "ONGC.NS",
    "Bharat Petroleum Corporation": "BPCL.NS",
    "LTIMindtree": "LTIM.NS",
    "Tata Consumer Products": "TATACONSUM.NS",
    "UPL": "UPL.NS",

    # ---------------- Nifty Next 50 / Other large & mid cap ----------------
    "Adani Green Energy": "ADANIGREEN.NS",
    "Adani Power": "ADANIPOWER.NS",
    "Adani Total Gas": "ATGL.NS",
    "Adani Transmission": "ADANITRANS.NS",
    "Ambuja Cements": "AMBUJACEM.NS",
    "ACC": "ACC.NS",
    "Avenue Supermarts (DMart)": "DMART.NS",
    "Bandhan Bank": "BANDHANBNK.NS",
    "Bank of Baroda": "BANKBARODA.NS",
    "Berger Paints India": "BERGEPAINT.NS",
    "Bharat Electronics": "BEL.NS",
    "Bharat Forge": "BHARATFORG.NS",
    "Biocon": "BIOCON.NS",
    "Bosch": "BOSCHLTD.NS",
    "Canara Bank": "CANBK.NS",
    "Cadila Healthcare (Zydus Lifesciences)": "ZYDUSLIFE.NS",
    "Chola Investment and Finance": "CHOLAFIN.NS",
    "Colgate-Palmolive India": "COLPAL.NS",
    "Container Corporation of India": "CONCOR.NS",
    "Dabur India": "DABUR.NS",
    "DLF": "DLF.NS",
    "GAIL India": "GAIL.NS",
    "Godrej Consumer Products": "GODREJCP.NS",
    "Godrej Properties": "GODREJPROP.NS",
    "Havells India": "HAVELLS.NS",
    "Hindustan Aeronautics": "HAL.NS",
    "Hindustan Petroleum Corporation": "HINDPETRO.NS",
    "Hindustan Zinc": "HINDZINC.NS",
    "ICICI Lombard General Insurance": "ICICIGI.NS",
    "ICICI Prudential Life Insurance": "ICICIPRULI.NS",
    "IDBI Bank": "IDBI.NS",
    "IDFC First Bank": "IDFCFIRSTB.NS",
    "Indian Oil Corporation": "IOC.NS",
    "Indian Railway Catering and Tourism Corp": "IRCTC.NS",
    "Indraprastha Gas": "IGL.NS",
    "Info Edge India (Naukri)": "NAUKRI.NS",
    "Interglobe Aviation (IndiGo)": "INDIGO.NS",
    "Jindal Steel & Power": "JINDALSTEL.NS",
    "Jubilant Foodworks": "JUBLFOOD.NS",
    "L&T Finance Holdings": "LTF.NS",
    "L&T Technology Services": "LTTS.NS",
    "LIC Housing Finance": "LICHSGFIN.NS",
    "Life Insurance Corporation of India": "LICI.NS",
    "Lupin": "LUPIN.NS",
    "Marico": "MARICO.NS",
    "Max Financial Services": "MFSL.NS",
    "MRF": "MRF.NS",
    "Muthoot Finance": "MUTHOOTFIN.NS",
    "National Aluminium Company": "NATIONALUM.NS",
    "National Mineral Development Corp": "NMDC.NS",
    "Oberoi Realty": "OBEROIRLTY.NS",
    "Oracle Financial Services Software": "OFSS.NS",
    "Page Industries": "PAGEIND.NS",
    "Petronet LNG": "PETRONET.NS",
    "Pidilite Industries": "PIDILITIND.NS",
    "PI Industries": "PIIND.NS",
    "Piramal Enterprises": "PEL.NS",
    "PNB Housing Finance": "PNBHOUSING.NS",
    "Punjab National Bank": "PNB.NS",
    "REC Limited": "RECLTD.NS",
    "SAIL (Steel Authority of India)": "SAIL.NS",
    "Samvardhana Motherson International": "MOTHERSON.NS",
    "Shriram Finance": "SHRIRAMFIN.NS",
    "Siemens": "SIEMENS.NS",
    "SRF": "SRF.NS",
    "Tata Chemicals": "TATACHEM.NS",
    "Tata Communications": "TATACOMM.NS",
    "Tata Elxsi": "TATAELXSI.NS",
    "Tata Power Company": "TATAPOWER.NS",
    "Torrent Pharmaceuticals": "TORNTPHARM.NS",
    "Torrent Power": "TORNTPOWER.NS",
    "Trent": "TRENT.NS",
    "TVS Motor Company": "TVSMOTOR.NS",
    "United Breweries": "UBL.NS",
    "United Spirits": "MCDOWELL-N.NS",
    "Vedanta": "VEDL.NS",
    "Voltas": "VOLTAS.NS",
    "Yes Bank": "YESBANK.NS",
    "Zee Entertainment Enterprises": "ZEEL.NS",
    "Zomato": "ZOMATO.NS",

    # ---------------- IT / Tech ----------------
    "Mphasis": "MPHASIS.NS",
    "Persistent Systems": "PERSISTENT.NS",
    "Coforge": "COFORGE.NS",
    "Mindtree (legacy, merged into LTIM)": "MINDTREE.NS",
    "Larsen & Toubro Infotech (legacy)": "LTI.NS",
    "Zensar Technologies": "ZENSARTECH.NS",
    "Cyient": "CYIENT.NS",
    "Firstsource Solutions": "FSL.NS",
    "Route Mobile": "ROUTE.NS",
    "Newgen Software Technologies": "NEWGEN.NS",
    "Intellect Design Arena": "INTELLECT.NS",
    "Sonata Software": "SONATSOFTW.NS",
    "Happiest Minds Technologies": "HAPPSTMNDS.NS",
    "KPIT Technologies": "KPITTECH.NS",
    "Tata Technologies": "TATATECH.NS",
    "Affle India": "AFFLE.NS",
    "Latent View Analytics": "LATENTVIEW.NS",

    # ---------------- Banking & Financial Services ----------------
    "Federal Bank": "FEDERALBNK.NS",
    "RBL Bank": "RBLBANK.NS",
    "AU Small Finance Bank": "AUBANK.NS",
    "Equitas Small Finance Bank": "EQUITASBNK.NS",
    "City Union Bank": "CUB.NS",
    "Karur Vysya Bank": "KARURVYSYA.NS",
    "South Indian Bank": "SOUTHBANK.NS",
    "Union Bank of India": "UNIONBANK.NS",
    "Indian Bank": "INDIANB.NS",
    "Bank of India": "BANKINDIA.NS",
    "Central Bank of India": "CENTRALBK.NS",
    "UCO Bank": "UCOBANK.NS",
    "Bank of Maharashtra": "MAHABANK.NS",
    "Punjab & Sind Bank": "PSB.NS",
    "Jammu & Kashmir Bank": "J&KBANK.NS",
    "Cholamandalam Financial Holdings": "CHOLAHLDNG.NS",
    "Aditya Birla Capital": "ABCAPITAL.NS",
    "Aditya Birla Sun Life AMC": "ABSLAMC.NS",
    "HDFC Asset Management Company": "HDFCAMC.NS",
    "Nippon Life India Asset Management": "NAM-INDIA.NS",
    "UTI Asset Management Company": "UTIAMC.NS",
    "Bajaj Holdings & Investment": "BAJAJHLDNG.NS",
    "Manappuram Finance": "MANAPPURAM.NS",
    "IIFL Finance": "IIFL.NS",
    "Poonawalla Fincorp": "POONAWALLA.NS",
    "Sundaram Finance": "SUNDARMFIN.NS",
    "Bajaj Consumer Care": "BAJAJCON.NS",
    "Central Depository Services": "CDSL.NS",
    "National Securities Depository": "NSDL.NS",
    "Multi Commodity Exchange of India": "MCX.NS",
    "BSE Limited": "BSE.NS",
    "Computer Age Management Services": "CAMS.NS",
    "Indian Energy Exchange": "IEX.NS",
    "SBI Cards and Payment Services": "SBICARD.NS",
    "PB Fintech (Policybazaar)": "POLICYBZR.NS",
    "Star Health and Allied Insurance": "STARHEALTH.NS",
    "General Insurance Corporation of India": "GICRE.NS",
    "New India Assurance": "NIACL.NS",
    "Go Digit General Insurance": "GODIGIT.NS",

    # ---------------- Pharma / Healthcare ----------------
    "Alkem Laboratories": "ALKEM.NS",
    "Aurobindo Pharma": "AUROPHARMA.NS",
    "Ipca Laboratories": "IPCALAB.NS",
    "Glenmark Pharmaceuticals": "GLENMARK.NS",
    "Mankind Pharma": "MANKIND.NS",
    "Laurus Labs": "LAURUSLABS.NS",
    "Gland Pharma": "GLAND.NS",
    "Abbott India": "ABBOTINDIA.NS",
    "Pfizer India": "PFIZER.NS",
    "GlaxoSmithKline Pharmaceuticals": "GLAXO.NS",
    "Sanofi India": "SANOFI.NS",
    "Natco Pharma": "NATCOPHARM.NS",
    "Ajanta Pharma": "AJANTPHARM.NS",
    "J B Chemicals & Pharmaceuticals": "JBCHEPHARM.NS",
    "Fortis Healthcare": "FORTIS.NS",
    "Max Healthcare Institute": "MAXHEALTH.NS",
    "Global Health (Medanta)": "MEDANTA.NS",
    "Narayana Hrudayalaya": "NH.NS",
    "Metropolis Healthcare": "METROPOLIS.NS",
    "Dr Lal PathLabs": "LALPATHLAB.NS",
    "Syngene International": "SYNGENE.NS",
    "Piramal Pharma": "PPLPHARMA.NS",
    "Sun Pharma Advanced Research": "SPARC.NS",
    "Wockhardt": "WOCKPHARMA.NS",
    "Granules India": "GRANULES.NS",
    "Suven Pharmaceuticals": "SUVENPHAR.NS",
    "Caplin Point Laboratories": "CAPLIPOINT.NS",
    "Krishna Institute of Medical Sciences": "KIMS.NS",

    # ---------------- Auto & Auto Ancillaries ----------------
    "Ashok Leyland": "ASHOKLEY.NS",
    "Escorts Kubota": "ESCORTS.NS",
    "Force Motors": "FORCEMOT.NS",
    "Exide Industries": "EXIDEIND.NS",
    "Amara Raja Energy & Mobility": "ARE&M.NS",
    "Balkrishna Industries": "BALKRISIND.NS",
    "MRF Tyres (see MRF above)": "MRF.NS",
    "Apollo Tyres": "APOLLOTYRE.NS",
    "CEAT": "CEATLTD.NS",
    "JK Tyre & Industries": "JKTYRE.NS",
    "Sona BLW Precision Forgings": "SONACOMS.NS",
    "Craftsman Automation": "CRAFTSMAN.NS",
    "Endurance Technologies": "ENDURANCE.NS",
    "Minda Corporation": "MINDACORP.NS",
    "Uno Minda": "UNOMINDA.NS",
    "Motherson Sumi Wiring India": "MSUMI.NS",
    "Bharat Gears": "BHARATGEAR.NS",
    "Rico Auto Industries": "RICOAUTO.NS",
    "Mahindra CIE Automotive": "MAHINDCIE.NS",
    "Varroc Engineering": "VARROC.NS",

    # ---------------- FMCG / Consumer ----------------
    "Godfrey Phillips India": "GODFRYPHLP.NS",
    "Emami": "EMAMILTD.NS",
    "Gillette India": "GILLETTE.NS",
    "Procter & Gamble Hygiene and Health Care": "PGHH.NS",
    "Jyothy Labs": "JYOTHYLAB.NS",
    "Bikaji Foods International": "BIKAJI.NS",
    "Radico Khaitan": "RADICO.NS",
    "Varun Beverages": "VBL.NS",
    "CCL Products India": "CCL.NS",
    "Tata Coffee (see Tata Consumer)": "TATACONSUM.NS",
    "Zydus Wellness": "ZYDUSWELL.NS",
    "Honasa Consumer (Mamaearth)": "HONASA.NS",
    "V-Mart Retail": "VMART.NS",
    "Aditya Birla Fashion and Retail": "ABFRL.NS",
    "Shoppers Stop": "SHOPERSTOP.NS",
    "Vedant Fashions (Manyavar)": "VEDANTFASHN.NS",
    "Metro Brands": "METROBRAND.NS",
    "Relaxo Footwears": "RELAXO.NS",
    "Bata India": "BATAINDIA.NS",
    "Campus Activewear": "CAMPUS.NS",

    # ---------------- Cement / Construction Materials ----------------
    "Dalmia Bharat": "DALBHARAT.NS",
    "JK Cement": "JKCEMENT.NS",
    "The Ramco Cements": "RAMCOCEM.NS",
    "Birla Corporation": "BIRLACORPN.NS",
    "Heidelberg Cement India": "HEIDELBERG.NS",
    "Prism Johnson": "PRSMJOHNSN.NS",
    "Star Cement": "STARCEMENT.NS",
    "Kajaria Ceramics": "KAJARIACER.NS",
    "Cera Sanitaryware": "CERA.NS",
    "Century Plyboards India": "CENTURYPLY.NS",
    "Greenpanel Industries": "GREENPANEL.NS",

    # ---------------- Metals & Mining ----------------
    "Vedanta (see above)": "VEDL.NS",
    "Jindal Stainless": "JSL.NS",
    "APL Apollo Tubes": "APLAPOLLO.NS",
    "Welspun Corp": "WELCORP.NS",
    "Ratnamani Metals and Tubes": "RATNAMANI.NS",
    "MOIL": "MOIL.NS",
    "Hindustan Copper": "HINDCOPPER.NS",
    "Jindal Saw": "JINDALSAW.NS",
    "Nalco (see National Aluminium)": "NATIONALUM.NS",

    # ---------------- Oil, Gas & Energy ----------------
    "Oil India": "OIL.NS",
    "Mangalore Refinery and Petrochemicals": "MRPL.NS",
    "Chennai Petroleum Corporation": "CHENNPETRO.NS",
    "Gujarat Gas": "GUJGASLTD.NS",
    "Gujarat State Petronet": "GSPL.NS",
    "Aegis Logistics": "AEGISCHEM.NS",
    "NHPC": "NHPC.NS",
    "SJVN": "SJVN.NS",
    "Torrent Power (see above)": "TORNTPOWER.NS",
    "JSW Energy": "JSWENERGY.NS",
    "CESC": "CESC.NS",
    "Adani Green Energy (see above)": "ADANIGREEN.NS",
    "Suzlon Energy": "SUZLON.NS",
    "Inox Wind": "INOXWIND.NS",
    "Websol Energy System": "WEBELSOLAR.NS",
    "KPI Green Energy": "KPIGREEN.NS",

    # ---------------- Capital Goods / Industrials ----------------
    "ABB India": "ABB.NS",
    "Cummins India": "CUMMINSIND.NS",
    "Thermax": "THERMAX.NS",
    "BHEL (Bharat Heavy Electricals)": "BHEL.NS",
    "Larsen & Toubro (see above)": "LT.NS",
    "Kirloskar Oil Engines": "KIRLOSENG.NS",
    "Kirloskar Brothers": "KIRLOSBROS.NS",
    "Timken India": "TIMKEN.NS",
    "SKF India": "SKFINDIA.NS",
    "Schaeffler India": "SCHAEFFLER.NS",
    "Honeywell Automation India": "HONAUT.NS",
    "GE T&D India": "GET&D.NS",
    "CG Power and Industrial Solutions": "CGPOWER.NS",
    "Hitachi Energy India": "POWERINDIA.NS",
    "Triveni Turbine": "TRITURBINE.NS",
    "Elgi Equipments": "ELGIEQUIP.NS",
    "AIA Engineering": "AIAENG.NS",
    "Carborundum Universal": "CARBORUNIV.NS",
    "Grindwell Norton": "GRINDWELL.NS",
    "Praj Industries": "PRAJIND.NS",
    "Astral": "ASTRAL.NS",
    "Supreme Industries": "SUPREMEIND.NS",
    "Finolex Cables": "FINCABLES.NS",
    "Finolex Industries": "FINPIPE.NS",
    "Polycab India": "POLYCAB.NS",
    "KEI Industries": "KEI.NS",
    "V-Guard Industries": "VGUARD.NS",
    "Dixon Technologies": "DIXON.NS",
    "Amber Enterprises India": "AMBER.NS",
    "Blue Star": "BLUESTARCO.NS",
    "Whirlpool of India": "WHIRLPOOL.NS",
    "Crompton Greaves Consumer Electricals": "CROMPTON.NS",
    "Orient Electric": "ORIENTELEC.NS",
    "Bharat Dynamics": "BDL.NS",
    "Mazagon Dock Shipbuilders": "MAZDOCK.NS",
    "Cochin Shipyard": "COCHINSHIP.NS",
    "Garden Reach Shipbuilders & Engineers": "GRSE.NS",
    "Hindustan Shipyard": "HSCL.NS",
    "Bharat Earth Movers (BEML)": "BEML.NS",
    "Ircon International": "IRCON.NS",
    "RITES": "RITES.NS",
    "Engineers India": "ENGINERSIN.NS",
    "NBCC India": "NBCC.NS",
    "Rail Vikas Nigam": "RVNL.NS",
    "Titagarh Rail Systems": "TITAGARH.NS",
    "Texmaco Rail & Engineering": "TEXRAIL.NS",

    # ---------------- Real Estate & Infrastructure ----------------
    "Macrotech Developers (Lodha)": "LODHA.NS",
    "Prestige Estates Projects": "PRESTIGE.NS",
    "Phoenix Mills": "PHOENIXLTD.NS",
    "Brigade Enterprises": "BRIGADE.NS",
    "Sobha": "SOBHA.NS",
    "Sunteck Realty": "SUNTECK.NS",
    "Mahindra Lifespace Developers": "MAHLIFE.NS",
    "Signature Global (India)": "SIGNATURE.NS",
    "IRB Infrastructure Developers": "IRB.NS",
    "GMR Airports Infrastructure": "GMRINFRA.NS",
    "GVK Power & Infrastructure": "GVKPIL.NS",
    "Adani Road Transport (unlisted, placeholder)": "ADANIENT.NS",
    "KNR Constructions": "KNRCON.NS",
    "PNC Infratech": "PNCINFRA.NS",
    "Dilip Buildcon": "DBL.NS",
    "HG Infra Engineering": "HGINFRA.NS",
    "Ashoka Buildcon": "ASHOKA.NS",
    "J Kumar Infraprojects": "JKIL.NS",
    "Nagarjuna Construction Company (NCC)": "NCC.NS",
    "Gujarat Pipavav Port": "GPPL.NS",
    "JSW Infrastructure": "JSWINFRA.NS",

    # ---------------- Telecom / Media / Internet ----------------
    "Vodafone Idea": "IDEA.NS",
    "Tata Teleservices (Maharashtra)": "TTML.NS",
    "PVR Inox": "PVRINOX.NS",
    "Sun TV Network": "SUNTV.NS",
    "TV18 Broadcast": "TV18BRDCST.NS",
    "Network18 Media & Investments": "NETWORK18.NS",
    "Dish TV India": "DISHTV.NS",
    "Nazara Technologies": "NAZARA.NS",
    "Just Dial": "JUSTDIAL.NS",
    "One97 Communications (Paytm)": "PAYTM.NS",
    "FSN E-Commerce Ventures (Nykaa)": "NYKAA.NS",
    "Delhivery": "DELHIVERY.NS",
    "Honasa Consumer (see above)": "HONASA.NS",
    "MapMyIndia (CE Info Systems)": "MAPMYINDIA.NS",
    "Indiamart Intermesh": "INDIAMART.NS",
    "Matrimony.com": "MATRIMONY.NS",

    # ---------------- Chemicals & Fertilizers ----------------
    "Deepak Nitrite": "DEEPAKNTR.NS",
    "Aarti Industries": "AARTIIND.NS",
    "Navin Fluorine International": "NAVINFLUOR.NS",
    "Gujarat Fluorochemicals": "FLUOROCHEM.NS",
    "Atul": "ATUL.NS",
    "Vinati Organics": "VINATIORGA.NS",
    "Balaji Amines": "BALAMINES.NS",
    "Alkyl Amines Chemicals": "ALKYLAMINE.NS",
    "Clean Science and Technology": "CLEAN.NS",
    "Fine Organic Industries": "FINEORG.NS",
    "Coromandel International": "COROMANDEL.NS",
    "Chambal Fertilisers and Chemicals": "CHAMBLFERT.NS",
    "Rashtriya Chemicals & Fertilizers": "RCF.NS",
    "GNFC (Gujarat Narmada Valley Fertilizers)": "GNFC.NS",
    "Gujarat Alkalies and Chemicals": "GUJALKALI.NS",
    "Tata Chemicals (see above)": "TATACHEM.NS",
    "Solar Industries India": "SOLARINDS.NS",
    "Linde India": "LINDEINDIA.NS",
    "SRF (see above)": "SRF.NS",
    "PI Industries (see above)": "PIIND.NS",
    "UPL (see above)": "UPL.NS",
    "Bayer CropScience (India)": "BAYERCROP.NS",
    "Rallis India": "RALLIS.NS",
    "Sumitomo Chemical India": "SUMICHEM.NS",
    "Aarti Pharmalabs": "AARTIPHARM.NS",

    # ---------------- Textiles ----------------
    "Raymond": "RAYMOND.NS",
    "Vardhman Textiles": "VTL.NS",
    "Trident": "TRIDENT.NS",
    "Welspun Living": "WELSPUNLIV.NS",
    "KPR Mill": "KPRMILL.NS",
    "Page Industries (see above)": "PAGEIND.NS",
    "Gokaldas Exports": "GOKEX.NS",
    "Arvind": "ARVIND.NS",
    "Siyaram Silk Mills": "SIYSIL.NS",
    "SP Apparels": "SPAL.NS",

    # ---------------- Airlines / Logistics / Shipping ----------------
    "SpiceJet": "SPICEJET.NS",
    "Blue Dart Express": "BLUEDART.NS",
    "TCI (Transport Corporation of India)": "TCI.NS",
    "VRL Logistics": "VRLLOG.NS",
    "Mahindra Logistics": "MAHLOG.NS",
    "Great Eastern Shipping Company": "GESHIP.NS",
    "Shipping Corporation of India": "SCI.NS",
    "Allcargo Logistics": "ALLCARGO.NS",
    "Gateway Distriparks": "GATEWAY.NS",

    # ---------------- Diversified / Conglomerates ----------------
    "ITC (see above)": "ITC.NS",
    "Adani Wilmar": "AWL.NS",
    "Godrej Industries": "GODREJIND.NS",
    "Bajaj Holdings (see above)": "BAJAJHLDNG.NS",
    "3M India": "3MINDIA.NS",
    "Aditya Birla Fashion (see above)": "ABFRL.NS",
    "Century Textiles and Industries": "CENTURYTEX.NS",
    "JSW Holdings": "JSWHL.NS",
    "Reliance Power": "RPOWER.NS",
    "Reliance Infrastructure": "RELINFRA.NS",
    "Reliance Capital": "RELCAPITAL.NS",
    "Future Retail": "FRETAIL.NS",
    "Future Consumer": "FCONSUMER.NS",

    # ---------------- Agri / Sugar ----------------
    "Balrampur Chini Mills": "BALRAMCHIN.NS",
    "EID Parry (India)": "EIDPARRY.NS",
    "Dhampur Sugar Mills": "DHAMPURSUG.NS",
    "Triveni Engineering & Industries": "TRIVENI.NS",
    "Bajaj Hindusthan Sugar": "BAJAJHIND.NS",
    "Godrej Agrovet": "GODREJAGRO.NS",
    "UPL (see above)": "UPL.NS",
    "Kaveri Seed Company": "KSCL.NS",

    # ---------------- Gems, Jewellery, Misc Consumer ----------------
    "Titan Company (see above)": "TITAN.NS",
    "Kalyan Jewellers India": "KALYANKJIL.NS",
    "PC Jeweller": "PCJEWELLER.NS",
    "Rajesh Exports": "RAJESHEXPO.NS",
    "Thangamayil Jewellery": "THANGAMAYL.NS",
    "Senco Gold": "SENCO.NS",

    # ---------------- New-age / Recently listed ----------------
    "Zomato (see above)": "ZOMATO.NS",
    "PB Fintech (see above)": "POLICYBZR.NS",
    "CarTrade Tech": "CARTRADE.NS",
    "EaseMyTrip (Easy Trip Planners)": "EASEMYTRIP.NS",
    "Aptus Value Housing Finance India": "APTUS.NS",
    "Home First Finance Company India": "HOMEFIRST.NS",
    "Fusion Micro Finance": "FUSION.NS",
    "CreditAccess Grameen": "CREDITACC.NS",
    "Ujjivan Small Finance Bank": "UJJIVANSFB.NS",
    "Suryoday Small Finance Bank": "SURYODAY.NS",
    "ESAF Small Finance Bank": "ESAFSFB.NS",
    "Utkarsh Small Finance Bank": "UTKARSHBNK.NS",
    "Jio Financial Services": "JIOFIN.NS",
    "Aadhar Housing Finance": "AADHARHFC.NS",
    "India Shelter Finance Corporation": "INDIASHLTR.NS",
    "Awfis Space Solutions": "AWFIS.NS",
    "Go Fashion (India)": "GOCOLORS.NS",
    "Sula Vineyards": "SULA.NS",
    "Devyani International": "DEVYANI.NS",
    "Sapphire Foods India": "SAPPHIRE.NS",
    "Westlife Foodworld": "WESTLIFE.NS",
    "Restaurant Brands Asia (Burger King India)": "RBA.NS",
    "Barbeque Nation Hospitality": "BARBEQUE.NS",
    "Lemon Tree Hotels": "LEMONTREE.NS",
    "Indian Hotels Company": "INDHOTEL.NS",
    "EIH (Oberoi Hotels)": "EIHOTEL.NS",
    "Chalet Hotels": "CHALET.NS",
    "Mahindra Holidays & Resorts India": "MHRIL.NS",

    # ---------------- More Industrials / Small-Mid Cap ----------------
    "Cummins India (see above)": "CUMMINSIND.NS",
    "Bharat Heavy Electricals (see above)": "BHEL.NS",
    "Kirloskar Pneumatic": "KIRLPNU.NS",
    "Greaves Cotton": "GREAVESCOT.NS",
    "Wabco India (Sew Eurodrive)": "WABCOINDIA.NS",
    "Sundram Fasteners": "SUNDRMFAST.NS",
    "Fiem Industries": "FIEMIND.NS",
    "Jamna Auto Industries": "JAMNAAUTO.NS",
    "Gabriel India": "GABRIEL.NS",
    "Automotive Axles": "AUTOAXLES.NS",
    "Wheels India": "WHEELS.NS",
    "Steel Strips Wheels": "SSWL.NS",
    "Suprajit Engineering": "SUPRAJIT.NS",
    "Setco Automotive": "SETCO.NS",
    "Talbros Automotive Components": "TALBROAUTO.NS",
    "ZF Commercial Vehicle Control Systems India": "ZFCVINDIA.NS",
    "Igarashi Motors India": "IGARASHI.NS",

    # ---------------- Specialty / Niche ----------------
    "Vardhman Special Steels": "VSSL.NS",
    "Mishra Dhatu Nigam": "MIDHANI.NS",
    "Graphite India": "GRAPHITE.NS",
    "HEG": "HEG.NS",
    "Navin Fluorine (see above)": "NAVINFLUOR.NS",
    "Bombay Dyeing & Manufacturing": "BOMDYEING.NS",
    "Century Enka": "CENTENKA.NS",
    "Nocil": "NOCIL.NS",
    "Deepak Fertilisers and Petrochemicals": "DEEPAKFERT.NS",
    "GHCL": "GHCL.NS",
    "Meghmani Organics": "MEGH.NS",
    "Camlin Fine Sciences": "CAMLINFINE.NS",
    "Privi Speciality Chemicals": "PRIVISCL.NS",
    "Neogen Chemicals": "NEOGEN.NS",
    "Anupam Rasayan India": "ANURAS.NS",
    "PCBL (Phillips Carbon Black)": "PCBL.NS",
    "Himadri Speciality Chemical": "HSCL2.NS",

    # ---------------- Consumer Durables / Electronics ----------------
    "Havells India (see above)": "HAVELLS.NS",
    "Voltas (see above)": "VOLTAS.NS",
    "Bajaj Electricals": "BAJAJELEC.NS",
    "TTK Prestige": "TTKPRESTIG.NS",
    "Hawkins Cookers": "HAWKINCOOK.NS",
    "Symphony": "SYMPHONY.NS",
    "IFB Industries": "IFBIND.NS",
    "Rajesh Exports (see above)": "RAJESHEXPO.NS",
    "Amber Enterprises (see above)": "AMBER.NS",
    "Dixon Technologies (see above)": "DIXON.NS",
    "PG Electroplast": "PGEL.NS",
    "Kaynes Technology India": "KAYNES.NS",
    "Syrma SGS Technology": "SYRMA.NS",
    "Cyient DLM": "CYIENTDLM.NS",
    "Avalon Technologies": "AVALON.NS",

    # ---------------- Education / Retail / Services ----------------
    "Info Edge (see above)": "NAUKRI.NS",
    "Aptech": "APTECHT.NS",
    "NIIT": "NIIT.NS",
    "NIIT Learning Systems": "NIITLTD.NS",
    "Career Point": "CAREERP.NS",
    "V-Mart Retail (see above)": "VMART.NS",
    "Trent (see above)": "TRENT.NS",
    "Spencer's Retail": "SPENCERS.NS",
    "Nykaa (see above)": "NYKAA.NS",
    "Zaggle Prepaid Ocean Services": "ZAGGLE.NS",

    # ---------------- Paints / Chemicals-consumer ----------------
    "Asian Paints (see above)": "ASIANPAINT.NS",
    "Berger Paints (see above)": "BERGEPAINT.NS",
    "Kansai Nerolac Paints": "KANSAINER.NS",
    "Akzo Nobel India": "AKZOINDIA.NS",
    "Indigo Paints": "INDIGOPNTS.NS",
    "Shalimar Paints": "SHALPAINTS.NS",

    # ---------------- Others / Diversified small caps ----------------
    "Zensar Technologies (see above)": "ZENSARTECH.NS",
    "Cera Sanitaryware (see above)": "CERA.NS",
    "Somany Ceramics": "SOMANYCERA.NS",
    "Orient Bell": "ORIENTBELL.NS",
    "HSIL (Hindware)": "HSIL.NS",
    "Cera (dup, see above)": "CERA.NS",
    "Century Plyboards (see above)": "CENTURYPLY.NS",
    "Greenlam Industries": "GREENLAM.NS",
    "Archidply Industries": "ARCHIDPLY.NS",

    # ================= EXPANSION BATCH 2 =================

    # ---------------- More PSU / Government-owned ----------------
    "Indian Renewable Energy Development Agency (IREDA)": "IREDA.NS",
    "Power Finance Corporation": "PFC.NS",
    "Housing and Urban Development Corp (HUDCO)": "HUDCO.NS",
    "National Fertilizers": "NFL.NS",
    "Fertilizers and Chemicals Travancore (FACT)": "FACT.NS",
    "Madras Fertilizers": "MADRASFERT.NS",
    "Steel Authority of India (dup)": "SAIL.NS",
    "MSTC": "MSTCLTD.NS",
    "HMT": "HMT.NS",
    "Andrew Yule & Company": "ANDREWYU.NS",
    "Bharat Immunologicals and Biologicals Corp": "BIBCL.NS",
    "Central Bank of India (dup)": "CENTRALBK.NS",
    "IFCI": "IFCI.NS",
    "State Trading Corporation of India": "STCINDIA.NS",
    "PTC India": "PTC.NS",
    "Cochin Shipyard (dup)": "COCHINSHIP.NS",
    "Balmer Lawrie & Company": "BALMLAWRIE.NS",
    "SJVN (dup)": "SJVN.NS",
    "Kudremukh Iron Ore Company": "KIOCL.NS",
    "MMTC": "MMTC.NS",
    "Rail Vikas Nigam (dup)": "RVNL.NS",
    "Bharat Petroleum (dup)": "BPCL.NS",
    "Container Corporation (dup)": "CONCOR.NS",
    "GAIL Gas": "GAILGAS.NS",
    "Mahanagar Gas": "MGL.NS",
    "Rashtriya Ispat Nigam (RINL, unlisted, placeholder)": "SAIL.NS",
    "Neyveli Lignite Corporation (NLC India)": "NLCINDIA.NS",
    "Uranium Corporation of India (unlisted, placeholder)": "COALINDIA.NS",
    "Bharat Sanchar Nigam (BSNL, unlisted, placeholder)": "BHARTIARTL.NS",
    "ITI Limited": "ITI.NS",
    "Hindustan Cables (unlisted, placeholder)": "HAL.NS",
    "Indian Telephone Industries (dup)": "ITI.NS",
    "Bharat Coking Coal (subsidiary, placeholder)": "COALINDIA.NS",
    "Central Coalfields (subsidiary, placeholder)": "COALINDIA.NS",
    "Numaligarh Refinery (unlisted, placeholder)": "OIL.NS",
    "Manaksia": "MANAKSIA.NS",

    # ---------------- More PSU Banks (full coverage) ----------------
    "Punjab National Bank (dup)": "PNB.NS",
    "Bank of Baroda (dup)": "BANKBARODA.NS",
    "Canara Bank (dup)": "CANBK.NS",
    "Union Bank of India (dup)": "UNIONBANK.NS",
    "Indian Overseas Bank": "IOB.NS",

    # ---------------- Regional / Small Private Banks ----------------
    "Dhanlaxmi Bank": "DHANBANK.NS",
    "CSB Bank": "CSBBANK.NS",
    "Tamilnad Mercantile Bank": "TMB.NS",
    "DCB Bank": "DCBBANK.NS",
    "Karnataka Bank": "KTKBANK.NS",

    # ---------------- More NBFC / Financial Services ----------------
    "Mahindra & Mahindra Financial Services": "M&MFIN.NS",
    "Tata Investment Corporation": "TATAINVEST.NS",
    "Tata Capital (if listed) / placeholder": "TATAMOTORS.NS",
    "Indiabulls Housing Finance (Sammaan Capital)": "SAMMAANCAP.NS",
    "Indostar Capital Finance": "INDOSTAR.NS",
    "SBI Cards (dup)": "SBICARD.NS",
    "Can Fin Homes": "CANFINHOME.NS",
    "GIC Housing Finance": "GICHSGFIN.NS",
    "Repco Home Finance": "REPCOHOME.NS",
    "Motilal Oswal Financial Services": "MOTILALOFS.NS",
    "Angel One": "ANGELONE.NS",
    "5paisa Capital": "5PAISA.NS",
    "Geojit Financial Services": "GEOJITFSL.NS",
    "IIFL Securities": "IIFLSEC.NS",
    "JM Financial": "JMFINANCIL.NS",
    "Edelweiss Financial Services": "EDELWEISS.NS",
    "SMC Global Securities": "SMCGLOBAL.NS",
    "Nuvama Wealth Management": "NUVAMA.NS",
    "360 One WAM (IIFL Wealth)": "360ONE.NS",
    "Anand Rathi Wealth": "ANANDRATHI.NS",
    "Prudent Corporate Advisory Services": "PRUDENT.NS",
    "KFin Technologies": "KFINTECH.NS",
    "Multi Commodity Exchange (dup)": "MCX.NS",
    "Spandana Sphoorty Financial": "SPANDANA.NS",
    "Satin Creditcare Network": "SATIN.NS",
    "MAS Financial Services": "MASFIN.NS",
    "Capri Global Capital": "CGCL.NS",
    "Five-Star Business Finance": "FIVESTAR.NS",
    "SBFC Finance": "SBFC.NS",
    "Sammaan Capital (dup)": "SAMMAANCAP.NS",
    "Piramal Finance (placeholder, part of Piramal Enterprises)": "PEL.NS",
    "L&T Finance (dup)": "LTF.NS",
    "Cholamandalam Investment (dup)": "CHOLAFIN.NS",

    # ---------------- More Insurance ----------------
    "Bajaj Allianz (unlisted, part of Bajaj Finserv, placeholder)": "BAJAJFINSV.NS",
    "Reliance General Insurance (unlisted, placeholder)": "RELIANCE.NS",
    "Niva Bupa Health Insurance": "NIVABUPA.NS",
    "Medi Assist Healthcare Services": "MEDIASSIST.NS",

    # ---------------- Defense / Aerospace ----------------
    "Data Patterns (India)": "DATAPATTNS.NS",
    "Paras Defence and Space Technologies": "PARAS.NS",
    "Astra Microwave Products": "ASTRAMICRO.NS",
    "MTAR Technologies": "MTARTECH.NS",
    "Zen Technologies": "ZENTEC.NS",
    "Premier Explosives": "PREMEXPLN.NS",
    "Solar Industries (dup)": "SOLARINDS.NS",
    "Bharat Dynamics (dup)": "BDL.NS",
    "Hindustan Aeronautics (dup)": "HAL.NS",
    "Bharat Electronics (dup)": "BEL.NS",
    "Mishra Dhatu Nigam (dup)": "MIDHANI.NS",
    "Apollo Micro Systems": "APOLLO.NS",
    "DCX Systems": "DCXINDIA.NS",
    "Azad Engineering": "AZAD.NS",

    # ---------------- Renewable Energy / Power ----------------
    "Waaree Energies": "WAAREEENER.NS",
    "Premier Energies": "PREMIERENE.NS",
    "Websol Energy System (dup)": "WEBELSOLAR.NS",
    "Borosil Renewables": "BORORENEW.NS",
    "Orient Green Power": "GREENPOWER.NS",
    "Sterling and Wilson Renewable Energy": "SWSOLAR.NS",
    "Gensol Engineering": "GENSOL.NS",
    "Insolation Energy": "INSOLATION.NS",
    "KPI Green Energy (dup)": "KPIGREEN.NS",
    "Urja Global": "URJA.NS",
    "Indowind Energy": "INDOWIND.NS",
    "Adani Energy Solutions": "ADANIENSOL.NS",
    "NTPC Green Energy": "NTPCGREEN.NS",
    "JSW Energy (dup)": "JSWENERGY.NS",
    "Torrent Power (dup2)": "TORNTPOWER.NS",
    "Tata Power (dup)": "TATAPOWER.NS",

    # ---------------- Media / Entertainment (expanded) ----------------
    "PVR Inox (dup)": "PVRINOX.NS",
    "Saregama India": "SAREGAMA.NS",
    "Balaji Telefilms": "BALAJITELE.NS",
    "TV Today Network": "TVTODAY.NS",
    "Hathway Cable & Datacom": "HATHWAY.NS",
    "Den Networks": "DEN.NS",
    "Sun TV Network (dup)": "SUNTV.NS",
    "D B Corp (Dainik Bhaskar)": "DBCORP.NS",
    "HT Media": "HTMEDIA.NS",
    "Jagran Prakashan": "JAGRAN.NS",
    "Music Broadcast (Radio City)": "MUSICBROAD.NS",
    "Entertainment Network India (Radio Mirchi)": "ENIL.NS",
    "Ortel Communications": "ORTEL.NS",
    "Shemaroo Entertainment": "SHEMAROO.NS",
    "PVR (legacy, merged into PVR Inox)": "PVR.NS",

    # ---------------- E-commerce / New-age Tech (expanded) ----------------
    "Swiggy": "SWIGGY.NS",
    "FirstCry (Brainbees Solutions)": "FIRSTCRY.NS",
    "Ola Electric Mobility": "OLAELEC.NS",
    "Honasa Consumer (dup2)": "HONASA.NS",
    "TBO Tek": "TBOTEK.NS",
    "Unicommerce eSolutions": "UNICOMMERCE.NS",
    "Ixigo (Le Travenues Technology)": "IXIGO.NS",
    "MobiKwik (One MobiKwik Systems)": "MOBIKWIK.NS",
    "Aadhar Housing (dup)": "AADHARHFC.NS",
    "PN Gadgil Jewellers": "PNGJL.NS",
    "Vishal Mega Mart": "VMM.NS",
    "Sagility India": "SAGILITY.NS",
    "Northern Arc Capital": "NORTHARC.NS",
    "Garuda Construction and Engineering": "GARUDA.NS",
    "Concord Enviro Systems": "CONCORDBIO.NS",
    "Ventive Hospitality": "VENTIVE.NS",
    "Avanse Financial Services": "AVANSE.NS",

    # ---------------- Diagnostics / More Healthcare ----------------
    "Vijaya Diagnostic Centre": "VIJAYA.NS",
    "Thyrocare Technologies": "THYROCARE.NS",
    "Rainbow Children's Medicare": "RAINBOW.NS",
    "Aster DM Healthcare": "ASTERDM.NS",
    "Shalby": "SHALBY.NS",
    "Poly Medicure": "POLYMED.NS",
    "Windlas Biotech": "WINDLAS.NS",
    "Sequent Scientific": "SEQUENT.NS",
    "Strides Pharma Science": "STAR.NS",
    "Eris Lifesciences": "ERIS.NS",
    "Indoco Remedies": "INDOCO.NS",
    "FDC": "FDC.NS",
    "Marksans Pharma": "MARKSANS.NS",
    "Jubilant Pharmova": "JUBLPHARMA.NS",
    "Jubilant Ingrevia": "JUBLINGREA.NS",
    "Sun Pharma (dup)": "SUNPHARMA.NS",
    "Emcure Pharmaceuticals": "EMCURE.NS",
    "Akums Drugs and Pharmaceuticals": "AKUMS.NS",
    "Concord Biotech": "CONCORDBIO.NS",
    "Blue Jet Healthcare": "BLUEJET.NS",
    "ASK Automotive (unrelated, auto ancillary)": "ASKAUTOLTD.NS",

    # ---------------- Hospitality / Travel (expanded) ----------------
    "Thomas Cook (India)": "THOMASCOOK.NS",
    "Yatra Online": "YATRA.NS",
    "Cox & Kings (legacy)": "COXANDKING.NS",
    "SOTC Travel (part of Thomas Cook)": "THOMASCOOK.NS",
    "Wonderla Holidays": "WONDERLA.NS",
    "Adlabs Entertainment": "ADLABS.NS",
    "Taj GVK Hotels & Resorts": "TAJGVK.NS",
    "Royal Orchid Hotels": "ROHLTD.NS",
    "TCI Express": "TCIEXP.NS",

    # ---------------- Ports / Infra (expanded) ----------------
    "Adani Ports (dup)": "ADANIPORTS.NS",
    "JSW Infrastructure (dup)": "JSWINFRA.NS",
    "Essar Ports (unlisted, placeholder)": "ADANIPORTS.NS",
    "Gujarat Pipavav Port (dup)": "GPPL.NS",
    "Navkar Corporation": "NAVKARCORP.NS",
    "Adani Total Gas (dup)": "ATGL.NS",
    "GMR Airports (dup)": "GMRINFRA.NS",
    "IRB Infrastructure (dup)": "IRB.NS",
    "Sadbhav Engineering": "SADBHAV.NS",
    "Sadbhav Infrastructure Project": "SADBHIN.NS",
    "GR Infraprojects": "GRINFRA.NS",
    "Kalpataru Projects International": "KPIL.NS",
    "KEC International": "KEC.NS",
    "Techno Electric & Engineering": "TECHNOE.NS",
    "Skipper": "SKIPPER.NS",
    "Voltamp Transformers": "VOLTAMP.NS",
    "Transformers and Rectifiers India": "TARIL.NS",
    "Genus Power Infrastructures": "GENUSPOWER.NS",
    "HPL Electric & Power": "HPL.NS",

    # ---------------- Real Estate (expanded) ----------------
    "Anant Raj": "ANANTRAJ.NS",
    "Ashiana Housing": "ASHIANA.NS",
    "Kolte-Patil Developers": "KOLTEPATIL.NS",
    "Puravankara": "PURVA.NS",
    "Nirlon": "NIRLON.NS",
    "Indiabulls Real Estate (Embassy Developments)": "EMBASSY.NS",
    "Arvind SmartSpaces": "ARVSMART.NS",
    "Suraj Estate Developers": "SURAJEST.NS",
    "Keystone Realtors (Rustomjee)": "RUSTOMJEE.NS",
    "Ajmera Realty & Infra India": "AJMERA.NS",
    "Man Infraconstruction": "MANINFRA.NS",
    "Rustomjee (dup)": "RUSTOMJEE.NS",
    "Sunteck Realty (dup)": "SUNTECK.NS",

    # ---------------- Agro / Food Processing (expanded) ----------------
    "Britannia (dup)": "BRITANNIA.NS",
    "Heritage Foods": "HERITGFOOD.NS",
    "Hatsun Agro Product": "HATSUN.NS",
    "Kwality": "KWALITY.NS",
    "Parag Milk Foods": "PARAGMILK.NS",
    "Vadilal Industries": "VADILALIND.NS",
    "Prataap Snacks": "DIAMONDYD.NS",
    "DFM Foods": "DFMFOODS.NS",
    "Gujarat Ambuja Exports": "GAEL.NS",
    "Ruchi Soya (Patanjali Foods)": "PATANJALI.NS",
    "Adani Wilmar (dup)": "AWL.NS",
    "Agro Tech Foods": "ATFL.NS",
    "LT Foods (Daawat Rice)": "LTFOODS.NS",
    "KRBL": "KRBL.NS",
    "Kohinoor Foods": "KOHINOOR.NS",
    "Usher Agro": "USHERAGRO.NS",
    "Mangalam Seeds": "MSPL.NS",
    "Bombay Burmah Trading Corporation": "BBTC.NS",
    "Harrisons Malayalam": "HARRMALAYA.NS",
    "McLeod Russel India": "MCLEODRUSS.NS",
    "Tata Coffee (legacy)": "TATACOFFEE.NS",
    "Rossell India": "ROSSELLIND.NS",
    "Godrej Agrovet (dup)": "GODREJAGRO.NS",
    "Dhanuka Agritech": "DHANUKA.NS",
    "Insecticides India": "INSECTICID.NS",
    "Bharat Rasayan": "BHARATRAS.NS",
    "Sharda Cropchem": "SHARDACROP.NS",
    "Excel Industries": "EXCELINDUS.NS",
    "Punjab Chemicals and Crop Protection": "PUNJABCHEM.NS",
    "Heranba Industries": "HERANBA.NS",
    "Best Agrolife": "BESTAGRO.NS",

    # ---------------- Steel / Metals (expanded) ----------------
    "JSW Steel (dup)": "JSWSTEEL.NS",
    "Jindal Steel & Power (dup)": "JINDALSTEL.NS",
    "Jindal Stainless (dup)": "JSL.NS",
    "Kalyani Steels": "KSL.NS",
    "Godawari Power & Ispat": "GPIL.NS",
    "Shyam Metalics and Energy": "SHYAMMETL.NS",
    "Electrosteel Castings": "ELECTCAST.NS",
    "Maharashtra Seamless": "MAHSEAMLES.NS",
    "Man Industries (India)": "MANINDS.NS",
    "Surya Roshni": "SURYAROSNI.NS",
    "Jai Balaji Industries": "JAIBALAJI.NS",
    "Sarda Energy & Minerals": "SARDAEN.NS",
    "Prakash Industries": "PRAKASH.NS",
    "Usha Martin": "USHAMART.NS",
    "Vardhman Special Steels (dup)": "VSSL.NS",
    "Rathi Steel and Power (unlisted, placeholder)": "SAIL.NS",
    "Adhunik Metaliks (legacy)": "ADHUNIK.NS",
    "Welspun Specialty Solutions": "WELSPUNLIV.NS",
    "APL Apollo Tubes (dup)": "APLAPOLLO.NS",

    # ---------------- Consumer / Retail (further expansion) ----------------
    "Titan Company (dup2)": "TITAN.NS",
    "Reliance Retail (unlisted, part of Reliance Industries, placeholder)": "RELIANCE.NS",
    "Landmark Cars": "LANDMARK.NS",
    "V2 Retail": "V2RETAIL.NS",
    "Style Spa Furniture (unlisted, placeholder)": "IKIO.NS",
    "IKIO Lighting": "IKIO.NS",
    "Safari Industries (India)": "SAFARI.NS",
    "VIP Industries": "VIPIND.NS",
    "Genesco (unrelated intl, excluded placeholder)": "RELAXO.NS",
    "Liberty Shoes": "LIBERTSHOE.NS",
    "Khadim India": "KHADIM.NS",
    "Mirza International": "MIRZAINT.NS",
    "Sheela Foam (Sleepwell)": "SFL.NS",
    "Nilkamal": "NILKAMAL.NS",
    "Cello World": "CELLO.NS",
    "Stove Kraft": "STOVEKRAFT.NS",
    "Butterfly Gandhimathi Appliances": "BUTTERFLY.NS",
    "Hindware Home Innovation": "HINDWAREAP.NS",

    # ---------------- Building Materials (expanded) ----------------
    "Pokarna": "POKARNA.NS",
    "Asian Granito India": "ASIANTILES.NS",
    "Nitco": "NITCO.NS",
    "Orient Cement": "ORIENTCEM.NS",
    "NCL Industries": "NCLIND.NS",
    "Sagar Cements": "SAGCEM.NS",
    "Deccan Cements": "DECCANCE.NS",
    "Panyam Cements": "PANYAMCEM.NS",
    "Everest Industries": "EVERESTIND.NS",
    "Visaka Industries": "VISAKAIND.NS",
    "HIL Limited": "HIL.NS",
    "Ramco Industries": "RAMCOIND.NS",

    # ---------------- Glass / Packaging ----------------
    "Borosil": "BOROSIL.NS",
    "HSIL Consumer (dup, see HSIL)": "HSIL.NS",
    "AGI Greenpac (HSIL renamed)": "AGI.NS",
    "Uflex": "UFLEX.NS",
    "Huhtamaki India": "HUHTAMAKI.NS",
    "EPL Limited (Essel Propack)": "EPL.NS",
    "TCPL Packaging": "TCPLPACK.NS",
    "Cosmo First": "COSMOFIRST.NS",
    "Jindal Poly Films": "JINDALPOLY.NS",
    "Time Technoplast": "TIMETECHNO.NS",
    "Polyplex Corporation": "POLYPLEX.NS",
    "Mold-Tek Packaging": "MOLDTKPAC.NS",

    # ---------------- Paper ----------------
    "JK Paper": "JKPAPER.NS",
    "West Coast Paper Mills": "WSTCSTPAPR.NS",
    "Century Textiles (dup, paper+textile)": "CENTURYTEX.NS",
    "Tamil Nadu Newsprint and Papers": "TNPL.NS",
    "Andhra Paper": "ANDHRAPAP.NS",
    "Seshasayee Paper and Boards": "SESHAPAPER.NS",
    "Emami Paper Mills": "EMAMIPAP.NS",
    "Orient Paper & Industries": "ORIENTPPR.NS",

    # ---------------- IT Hardware / Electronics Manufacturing (EMS) ----------------
    "Dixon Technologies (dup2)": "DIXON.NS",
    "Amber Enterprises (dup2)": "AMBER.NS",
    "Kaynes Technology (dup)": "KAYNES.NS",
    "Syrma SGS (dup)": "SYRMA.NS",
    "Netweb Technologies India": "NETWEB.NS",
    "Onward Technologies": "ONWARDTEC.NS",
    "Sify Technologies": "SIFY.NS",
    "Rail Tel Corporation of India": "RAILTEL.NS",
    "Tata Communications (dup)": "TATACOMM.NS",
    "GTPL Hathway": "GTPL.NS",
    "Vindhya Telelinks": "VINDHYATEL.NS",
    "HFCL": "HFCL.NS",
    "Sterlite Technologies": "STLTECH.NS",
    "ITI (dup)": "ITI.NS",
    "Tejas Networks": "TEJASNET.NS",
    "D-Link India": "DLINKINDIA.NS",
    "Genesys International": "GENESYS.NS",

    # ---------------- Diamond / Gems Export ----------------
    "Vaibhav Global": "VAIBHAVGBL.NS",
    "Renaissance Global": "RGL.NS",
    "Goldiam International": "GOLDIAM.NS",
    "Shrenuj & Company": "SHRENUJ.NS",
    "SEQUENT (dup, see Sequent Scientific)": "SEQUENT.NS",

    # ---------------- Miscellaneous / More small-mid caps ----------------
    "CarTrade Tech (dup)": "CARTRADE.NS",
    "Aptus Value Housing (dup)": "APTUS.NS",
    "Home First Finance (dup)": "HOMEFIRST.NS",
    "Rategain Travel Technologies": "RATEGAIN.NS",
    "Digitally Owned by Zaggle (dup)": "ZAGGLE.NS",
    "Info Edge (dup2)": "NAUKRI.NS",
    "Indiamart Intermesh (dup)": "INDIAMART.NS",
    "Just Dial (dup)": "JUSTDIAL.NS",
    "Nazara Technologies (dup)": "NAZARA.NS",
    "Delta Corp": "DELTACORP.NS",
    "Onmobile Global": "ONMOBILE.NS",
    "Mastek": "MASTEK.NS",
    "Ramco Systems": "RAMCOSYS.NS",
    "eClerx Services": "ECLERX.NS",
    "R Systems International": "RSYSTEMS.NS",
    "Datamatics Global Services": "DATAMATICS.NS",
    "Birlasoft": "BSOFT.NS",
    "Quess Corp": "QUESS.NS",
    "Team Lease Services": "TEAMLEASE.NS",
    "CIEL HR Services": "CIEL.NS",
    "3i Infotech": "3IINFOTECH.NS",
    "Subex": "SUBEXLTD.NS",
    "Majesco (legacy)": "MAJESCO.NS",
    "Nucleus Software Exports": "NUCLEUS.NS",
    "eMudhra": "EMUDHRA.NS",
    "Netsol Technologies India (unrelated intl, excluded placeholder)": "NUCLEUS.NS",
    "Cigniti Technologies": "CIGNITITEC.NS",
    "Sasken Technologies": "SASKEN.NS",
    "InfoBeans (merged, placeholder)": "MASTEK.NS",
    "Xchanging Solutions (legacy)": "XCHANGING.NS",
    "Polaris Consulting (legacy, now Virtusa placeholder)": "VIRTUSA.NS",

    # ---------------- Trading / Diversified Holding Companies ----------------
    "Bombay Stock Exchange (dup, see BSE)": "BSE.NS",
    "Investment corporations - Tata Investment (dup)": "TATAINVEST.NS",
    "Williamson Magor & Company": "WILLAMAGOR.NS",
    "Kesoram Industries": "KESORAMIND.NS",
    "DCM Shriram": "DCMSHRIRAM.NS",
    "DCM Shriram Industries": "DCMSRIND.NS",
    "Gulf Oil Lubricants India": "GULFOILLUB.NS",
    "Castrol India": "CASTROLIND.NS",
    "Savita Oil Technologies": "SOTL.NS",
    "Panama Petrochem": "PANAMAPET.NS",
    "Gulf Petrochem (unlisted, placeholder)": "GULFOILLUB.NS",

    # ---------------- Additional Auto (expanded) ----------------
    "Mahindra & Mahindra (dup)": "M&M.NS",
    "Force Motors (dup)": "FORCEMOT.NS",
    "SML Isuzu": "SMLISUZU.NS",
    "Olectra Greentech": "OLECTRA.NS",
    "JBM Auto": "JBMA.NS",
    "PPAP Automotive": "PPAP.NS",
    "Lumax Industries": "LUMAXIND.NS",
    "DCM Shriram Industries (dup)": "DCMSRIND.NS",
    "Denso India (unlisted, placeholder)": "MOTHERSON.NS",
    "Subros": "SUBROS.NS",
    "Munjal Auto Industries": "MUNJALAU.NS",
    "Munjal Showa": "MUNJALSHOW.NS",
    "Rane Holdings": "RANEHOLDIN.NS",
    "Rane Brake Lining": "RML.NS",
    "Rane Engine Valve": "RANEENGINE.NS",
    "Banco Products (India)": "BANCOINDIA.NS",
    "Precision Camshafts": "PRECAM.NS",
    "Shivam Autotech": "SHIVAMAUTO.NS",
    "Varroc Engineering (dup)": "VARROC.NS",
    "Hero Motors (unlisted, placeholder)": "HEROMOTOCO.NS",
    "TI Financial (Murugappa Group, placeholder)": "TIINDIA.NS",
    "Tube Investments of India": "TIINDIA.NS",

    # ---------------- More Cement / Infra Materials ----------------
    "India Cements": "INDIACEM.NS",
    "Mangalam Cement": "MANGLMCEM.NS",
    "KCP": "KCP.NS",
    "Barak Valley Cements": "BARAKVALLEY.NS",
    "Udaipur Cement Works": "UDAICEMENT.NS",

    # ---------------- Consumer Electricals / Wires ----------------
    "RR Kabel": "RRKABEL.NS",
    "Apar Industries": "APARINDS.NS",
    "Cords Cable Industries": "CORDSCABLE.NS",
    "Universal Cables": "UNIVCABLES.NS",
    "Paramount Communications": "PARACABLES.NS",
    "Diamond Power Infrastructure": "DIAPOWER.NS",

    # ---------------- More Chemicals ----------------
    "Godavari Biorefineries": "GODAVARIB.NS",
    "India Glycols": "INDIAGLYCO.NS",
    "Gujarat State Fertilizers & Chemicals": "GSFC.NS",
    "Nagarjuna Fertilizers and Chemicals": "NAGARFERT.NS",
    "Deepak Chemtex": "DEEPCHEM.NS",
    "Aether Industries": "AETHER.NS",
    "Yasho Industries": "YASHO.NS",
    "Miracle Electronics (unrelated placeholder)": "SOLARINDS.NS",
    "Rossari Biotech": "ROSSARI.NS",
    "Ami Organics": "AMIORG.NS",
    "Chemplast Sanmar": "CHEMPLASTS.NS",
    "DCW": "DCW.NS",
    "Tata Chemicals (dup2)": "TATACHEM.NS",
    "SI Group India (unlisted, placeholder)": "AARTIIND.NS",
    "Vishnu Chemicals": "VISHNU.NS",
    "Paushak": "PAUSHAKLTD.NS",

    # ---------------- Home / More Small Caps ----------------
    "Kaya (dup, see Marico placeholder)": "MARICO.NS",
    "VLCC Health Care (unlisted, placeholder)": "EMAMILTD.NS",
    "Jyothy Labs (dup)": "JYOTHYLAB.NS",
    "Sanofi Consumer Healthcare (unlisted, placeholder)": "SANOFI.NS",
    "Wipro Consumer Care (unlisted, part of Wipro Enterprises, placeholder)": "WIPRO.NS",
    "Emami Realty (unlisted, placeholder)": "EMAMILTD.NS",

    # ---------------- Additional Financial / Exchange ----------------
    "National Stock Exchange (unlisted, placeholder)": "BSE.NS",
    "CRISIL": "CRISIL.NS",
    "ICRA": "ICRA.NS",
    "CARE Ratings": "CARERATING.NS",
    "Acuite Ratings (unlisted, placeholder)": "CRISIL.NS",
    "SMIFS Capital Markets": "SMIFS.NS",

    # ---------------- Sports / Lifestyle ----------------
    "Delta Corp (dup)": "DELTACORP.NS",
    "Nazara (dup2)": "NAZARA.NS",
    "SG (Sanspareils Greenlands, unlisted, placeholder)": "RELAXO.NS",
    "Adani Sportsline (unlisted, placeholder)": "ADANIENT.NS",

    # ---------------- Water / Environment ----------------
    "VA Tech Wabag": "WABAG.NS",
    "Ion Exchange (India)": "IONEXCHANG.NS",
    "Thermax (dup)": "THERMAX.NS",
    "Va Tech Wabag (dup)": "WABAG.NS",
    "EMS Limited": "EMSLIMITED.NS",
    "Concord Enviro (dup, see Concord Biotech placeholder)": "CONCORDBIO.NS",
    "Vishnu Prakash R Punglia": "VPRPL.NS",
    "Ganesh Housing Corporation": "GANESHHOUC.NS",

    # ---------------- Battery / EV ----------------
    "Amara Raja (dup)": "ARE&M.NS",
    "Exide Industries (dup)": "EXIDEIND.NS",
    "HBL Power Systems": "HBLPOWER.NS",
    "Okaya Power (unlisted, placeholder)": "EXIDEIND.NS",
    "Tata Motors DVR (legacy)": "TATAMTRDVR.NS",
    "Ather Energy": "ATHERENERG.NS",
    "Ola Electric (dup)": "OLAELEC.NS",
    "JBM Auto (dup)": "JBMA.NS",
    "Servotech Renewable Power System": "SERVOTECH.NS",

    # ---------------- Miscellaneous Additional ----------------
    "Central Depository Services (dup)": "CDSL.NS",
    "Zydus Wellness (dup)": "ZYDUSWELL.NS",
    "GMM Pfaudler": "GMMPFAUDLR.NS",
    "Thermax (dup2)": "THERMAX.NS",
    "Kirloskar Ferrous Industries": "KIRLFER.NS",
    "Kirloskar Industries": "KIRLOSIND.NS",
    "Elecon Engineering Company": "ELECON.NS",
    "Shakti Pumps (India)": "SHAKTIPUMP.NS",
    "WPIL": "WPIL.NS",
    "KSB": "KSB.NS",
    "Ador Welding": "ADORWELD.NS",
    "Esab India": "ESABINDIA.NS",
    "Bharat Bijlee": "BBL.NS",
    "GE Power India": "GEPIL.NS",
    "Triveni Turbine (dup)": "TRITURBINE.NS",
    "TD Power Systems": "TDPOWERSYS.NS",
    "Inox Wind Energy": "INOXGREEN.NS",
    "Suzlon Energy (dup)": "SUZLON.NS",
    "Websol Energy (dup2)": "WEBELSOLAR.NS",
}

# Convenience: reverse lookup ticker -> display name
TICKER_TO_NAME = {v: k for k, v in COMPANIES.items()}


def company_count() -> int:
    return len(COMPANIES)
